### ISSUE TITLE
Multiple parallel uploads for single file?

### ISSUE THREAD

**Issue by ajarti** [ankitpokhrel/tus-php#100]
Hi guys,
            I am using Uppy with tus-php on Laravel. My understanding is that the tus protocol besides being more redundant would allow multiple parallel upload streams for a single file, thereby speeding it up.

I cannot for the life of me find any help on this .. I can only get a single path stream going, well that's what it looks like in chrome dev tools networking tab.

Any help is much appreciated.

**Comment by samundra** [comment]
Hey @ajarti 

Currently, Tus-php doesn't support parallel uploads. However, this is something that might be for the future versions.

@ankitpokhrel What do you think?

**Comment by ankitpokhrel** [comment]
@ajarti @samundra actually it can be done using concatenation extension as mentioned in this [blog post](https://tus.io/blog/2018/09/25/adoption.html).

<img width="1464" alt="concat" src="https://user-images.githubusercontent.com/2364546/47736335-17168f80-dca1-11e8-9e14-7450abd7999b.png">

We can use [tus-js client](https://github.com/tus/tus-js-client) and [tus-php server](https://github.com/ankitpokhrel/tus-php) to achieve this but it will require some custom development.

**Comment by ankitpokhrel** [comment]
@ajarti The process is perfectly described in this [blog post](https://abdelhady.net/2018/11/17/uploading-extremely-large-files-the-awesome-easy-way-tus-server/).
