### ISSUE TITLE
Clean cache after upload complete/success ?

### ISSUE THREAD

**Issue by AurelienMendes** [ankitpokhrel/tus-php#102]
Hi Ankit,

When I want to upload a file twice, the second time the upload is not sent since the HEAD request (200 OK) consider the file is fully uploaded (Eg : Upload-Length: 156354 && Upload-Offset: 156354) since the Server find in cache an 'offset' key ... 

So, would not it be better to remove the cache for files which has been successfully uploaded ?

Thank,
Aurélien

**Comment by ankitpokhrel** [comment]
> So, would not it be better to remove the cache for files which has been successfully uploaded ?

You can lower the cache TTL using [setTtl](https://github.com/ankitpokhrel/tus-php/blob/master/src/Cache/AbstractCache.php#L20) method. [Default TTL](https://github.com/ankitpokhrel/tus-php/blob/master/src/Cache/AbstractCache.php#L8) is 86400s (1 day).
