### ISSUE TITLE
How to do something on server when upload is completed? 

### ISSUE THREAD

**Issue by kurumbus** [ankitpokhrel/tus-php#106]
I would like to do some stuff when the upload is finished. (transcode uploaded file for example and uploaded it to S3). 

You mentioned in #65 that it can be done by middleware, but I honestly can't understand how.
Could you please give at least a general idea of how to go about it? I honestly tried, but can't grasp. 
Or instead of middleware should I do something like described here #57 ?

**Comment by ankitpokhrel** [comment]
@kurumbus no it can't be done with middleware. The package doesn't emit any hook/event after upload completes. One way it can be done is to get uploaded files from cache in server and process it from there.

**Comment by ankitpokhrel** [comment]
@kurumbus yes, adding hooks is in the project roadmap. I won't promise that it will be done anytime soon but of-course it will be added in the near future. PRs are welcome! :)

**Comment by kurumbus** [comment]
@ankitpokhrel  Well, honestly if somebody smarter than myself would help with the general principle, I could implement it and would be glad to help. But I'm not sure, what pattern to use here.

**Comment by ankitpokhrel** [comment]
@kurumbus initial support for events has been added: https://github.com/ankitpokhrel/tus-php#events

**Comment by kurumbus** [comment]
@ankitpokhrel Thank you!
