### ISSUE TITLE
Old version of Carbon

### ISSUE THREAD

**Issue by TCB13** [ankitpokhrel/tus-php#108]
Currently using 1.26.3. The latest version is 2.6, maybe an upgrade?

I believe the current version is locked on 1.26 because of Laravel, however there are other frameworks and contexts where running Carbon 2.6 is needed.

**Comment by ankitpokhrel** [comment]
@TCB13 can you try to install package from `issue-108` branch and check if it works.

```shell
$ composer require ankitpokhrel/tus-php:dev-issue-108
```

**Comment by TCB13** [comment]
@ankitpokhrel yes it does work. :)
