### ISSUE TITLE
Chunk upload

### ISSUE THREAD

**Issue by jcubic** [ankitpokhrel/tus-php#109]
I've just found this project and spec and it's pretty cool but I have question.

Is it possible to use this project and tos spec to upload file that is larger then file limit set by Apache server?

I have my own implementation of chunk upload for files larger then php limit. But it require to delete old file before upload because it use append to original file name.

And I was wandering if can I, with this pause/resume, upload using chunks?

**Comment by ankitpokhrel** [comment]
@jcubic Yes, you just need to send chunks less than limit set by your server. The process is more or less summed up in this [blog post](https://abdelhady.net/2018/11/17/uploading-extremely-large-files-the-awesome-easy-way-tus-server/).

**Comment by TCB13** [comment]
@jcubic as @ankitpokhrel explained the chunk functionality can be used for that. I'm currently doing it both for Apache and IIS.

**Comment by jcubic** [comment]
Awesome, thank you.
