### ISSUE TITLE
TusPhp\Middleware\Cors: Access-Control-Allow-Origin set as null

### ISSUE THREAD

**Issue by TCB13** [ankitpokhrel/tus-php#114]
**Describe the bug**

At the middleware `TusPhp\Middleware\Cor` its possible for the header `Access-Control-Allow-Origin` to be set as `null`. This can cause issues down the line, specially if you're trying to convert the TUS response into a PSR7 object using `Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory`.

Here is the affected chunk:

```
 public function handle(Request $request, Response $response)
    {
        $response->setHeaders([
            'Access-Control-Allow-Origin' => $request->header('Origin'),
            'Access-Control-Allow-Methods' => implode(',', $request->allowedHttpVerbs()),
```
If `$request->header('Origin')` returns `null` and we use the response with `DiactorosFactory` we get:
```
Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received NULL in ...vendor\zendframework\zend-diactoros\src\HeaderSecurity.php:139`
```

**Possible Solutions?**

- Only add this header if the result isn't null;
- Set as `*`

**Comment by TCB13** [comment]
I've submitted PR #115 to address this issue. Sets the header as `*` if the result is null.

**Comment by ankitpokhrel** [comment]
@TCB13 you can [create your own middleware](https://github.com/ankitpokhrel/tus-php#creating-a-middleware) and override `\TusPhp\Middleware\Cors` middleware.

```php
$server->middleware()
    ->skip(\TusPhp\Middleware\Cors::class)
    ->add(YourCustomCorsMiddleware::class);
```
