### ISSUE TITLE
File object missing checksum and key on concat

### ISSUE THREAD

**Issue by Fidelix** [ankitpokhrel/tus-php#120]
**Describe the bug**
The `File` object being inserted into the `tus-server.upload.merged` event is missing the upload key and the checksum.

They are defined but are never put back into the $file object:
https://github.com/ankitpokhrel/tus-php/blob/91f2f92e038dbd5e137743fb4ff0adc97d527eff/src/Tus/Server.php#L422

**To Reproduce**
1. Add a listener to the `tus-server.upload.merged` event;
2. Inspect `$file->details()` or attempt to `$file->getChecksum()`;
3. key and checksum are missing;

**Expected behavior**
The checksum and uploadKey need to be available on the merged event.

**Comment by ankitpokhrel** [comment]
Fixed in #122
