### ISSUE TITLE
Getting upload metadata for post upload processing

### ISSUE THREAD

**Issue by nanayaw-kirk** [ankitpokhrel/tus-php#124]
I have been able to integrate the protocol into an existing laravel project and I am able use the event hooks for post upload processing. However, fetching the form fields/meta field sent along (I am using uppy by the way) the upload is proving a pain. I can't seem to fetch it off the $event->getRequest() instance in the post upload event hook.
Any pointers?

**Comment by ankitpokhrel** [comment]
@nanayaw-kirk `$event->getRequest() ` is tus [Request](https://github.com/ankitpokhrel/tus-php/blob/master/src/Request.php) instance which will not have form fields details. You will need to get it from laravel request object inside the event hook.

**Comment by alhaji-aki** [comment]
@ankitpokhrel how do I get the laravel request object inside the event hook.

**Comment by ankitpokhrel** [comment]
@alhaji-aki you can get it from service container eg: `app('request')`

**Comment by alhaji-aki** [comment]
@ankitpokhrel I dumped the `app('request')` and its giving Me the laravel request object alright but it didn't contain the request parameters from my uppy form. I also noticed that the input fields that are added to uppy's metaFields didn't have a name attribute but rather a data-name attribute.

**Comment by alhaji-aki** [comment]
For anyone finding it difficult to get form fields from their request.

- Form fields are only available when the upload process starts so to get them u have to listen for `tus-server.upload.created` event.
- Then in the method where you are handling this event. The form fields are passed in the request header of the tus  [Request](https://github.com/ankitpokhrel/tus-php/blob/master/src/Request.php) instace which you can get in the event by `$event->getRequest()`. This request instance has an `extractMeta()` method you can use to get the form fields you passed. So say you have a form field with name `title` all you have to do in your event handler method is `$event->getRequest()->extractMeta('title')`.

Happy coding...
