### ISSUE TITLE
File name collision

### ISSUE THREAD

**Issue by anasser** [ankitpokhrel/tus-php#125]
Uploading two files with the same name appends their bytes to the same file on the server, resulting in corrupted files.

**Comment by ankitpokhrel** [comment]
@anasser Please refer to issue #52

**Comment by anasser** [comment]
Thank you very much for the quick response. I have used the workaround you mentioned in the other thread and it works fine.

I do not believe mixing files should be the default behaviour, however. Still thank you for this great work.
