### ISSUE TITLE
./vendor/bin/tus does not exist

### ISSUE THREAD

**Issue by Yangwendaxia** [ankitpokhrel/tus-php#127]
**Describe the bug**
execute 
```
composer require ankitpokhrel/tus-php
```
shows following error info
```
Skipped installation of bin bin/tus for package ankitpokhrel/tus-php: file not found in package
```
**To Reproduce**
1. composer require ankitpokhrel/tus-php

**Expected behavior**
no error occured.
**Screenshots**
![image](https://user-images.githubusercontent.com/3424048/51165954-dc55e800-18dc-11e9-94ac-9d81037e48b8.png)

**Comment by ankitpokhrel** [comment]
@Yangwendaxia can you try to fetch `issue-127` branch and see if it works

```shell
composer require ankitpokhrel/tus-php:dev-issue-127
```

**Comment by Yangwendaxia** [comment]
@ankitpokhrel issue-127 branch works fine.

**Comment by ankitpokhrel** [comment]
@Yangwendaxia Thanks for confirmation. I will make new release tonight (TH time).
