### ISSUE TITLE
Use in Yii 2.0

### ISSUE THREAD

**Issue by sjelfull** [ankitpokhrel/tus-php#131]
**Is your feature request related to a problem? Please describe.**
I'm trying to run this in a Yii 2 controller, but i'm finding that Yii is overriding certain things like the status code.

**Describe the solution you'd like**
It would be great if the sending of the response could be decoupled some how, so that I could use the Yii response/routing handling. Maybe some way to get the status code, headers and content and send it myself?

**Describe alternatives you've considered**
I've tried hacking the source code a bit, but the handlers is tightly coupled with sending the response, so I wasn't able to come up with any good solution.

Any ideas?

**Comment by sjelfull** [comment]
Turns out there is a `createOnly` option in the Response class.

Something like this worked for me:
```php
$server
            ->getResponse()
            ->createOnly(true);

        $response = $server->serve();

        $yiiResponse
            ->setStatusCode($response->getStatusCode());

        foreach ($response->headers->allPreserveCaseWithoutCookies() as $name => $values) {
            $replace = 0 === strcasecmp($name, 'Content-Type');

            foreach ($values as $value) {
                //header($name . ': ' . $value, $replace, $this->statusCode);
                $replace ?
                    $yiiResponse
                        ->getHeaders()
                        ->set($name, $value)
                    :
                    $yiiResponse
                        ->getHeaders()
                        ->add($name, $value);
            }
        }

        $response->sendContent();
        $yiiResponse->send();

        exit(0);
```

**Comment by ankitpokhrel** [comment]
@sjelfull thank you for creating an issue and posting your solution, It will help others 👏👏👏
