### ISSUE TITLE
OPTIONS response should have Tus-Resumable header

### ISSUE THREAD

**Issue by alucic** [ankitpokhrel/tus-php#134]
**OPTIONS response missing Tus-Resumable header**

I just glanced over the code and forgive me if I got it wrong. 
From what I see, GloablHeaders will exclude `Tus-Resumable` from OPTIONS response, which is not by the spec
https://github.com/ankitpokhrel/tus-php/blob/1c36d2d542d848036c6e1fe85e8e1bb22f64833a/src/Middleware/GlobalHeaders.php#L21-L23

`OPTIONS` request example from the specification https://tus.io/protocols/resumable-upload.html#options shows `Tus-Resumable` in the response

Go implementation has it
https://github.com/tus/tusd/issues/260#issuecomment-479649277

Node implementation has it
https://github.com/tus/tus-node-server/blob/f459c474327c0e4f384c9737392805a5ee14154a/lib/Server.js#L138

**Comment by ankitpokhrel** [comment]
Hi @alucic, thanks for reporting. Looks like I misinterpreted the statement in the spec. Are you able to send the PR?
