### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by jammersonf** [ankitpokhrel/tus-php#136]
Error:
> "message": "Client error: `SETKEY http://dev.bembras.api/75247b51bd97d93cd0094978a29b194e` resulted in a `405 Method Not Allowed`

web.php
![image](https://user-images.githubusercontent.com/2231447/55690196-8b4a1300-5964-11e9-83d0-0339a61a3a68.png)

TusServiceProvider.php
![image](https://user-images.githubusercontent.com/2231447/55675613-82d9d580-589b-11e9-8e03-e5d8485d7d89.png)

UploadController.php
```php
public function UploadTus()
{
    $client = new \GuzzleHttp\Client(['base_uri'=>'http://dev.bembras.api', 'debug'=> true]);
    // Alert: Sanitize all inputs properly in production code
    if (! empty($_FILES)) {
        $fileMeta  = $_FILES['tus_file'];
        $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

        try {
            $client->setKey($uploadKey)->file($fileMeta['tmp_name'], time() . '_' . $fileMeta['name']);
            $bytesUploaded = $client->upload(5000000); // Chunk of 5 mb
            echo json_encode([
                'status' => 'uploading',
                'bytes_uploaded' => $bytesUploaded,
                'upload_key' => $uploadKey
            ]);
        } catch (ConnectionException | FileException | TusException $e) {
            echo json_encode([
                'status' => 'error',
                'bytes_uploaded' => -1,
                'upload_key' => '',
                'error' => $e->getMessage(),
            ]);
        }
    } else {
        echo json_encode([
            'status' => 'error',
            'bytes_uploaded' => -1,
            'error' => 'No input!',
        ]);
    }
}
```

The Verify method is responding ok, the problem is only on upload.
Sorry for my bad English

**Comment by ankitpokhrel** [comment]
@jammersonf I see you are using Guzzle client to send the request to tus server. While that will work if you follow [the protocol](https://tus.io/protocols/resumable-upload.html) properly, it is recommended to use one of the already [available clients](https://tus.io/protocols/resumable-upload.html).

You can check [basic example implementation](https://github.com/ankitpokhrel/tus-php/tree/master/example/basic) if you want to use tus-php client.

**Comment by jammersonf** [comment]
@ankitpokhrel i changed for `$client = new \TusPhp\Tus\Client('http://dev.bembras.api')` and has passed. But i'm still in error

`Client error: `POST http://dev.bembras.api/files` resulted in a `404 Not Found` response:\nNo input file specified.\n\n",`

I already put the /files on virtualhost
![image](https://user-images.githubusercontent.com/2231447/55761692-92415600-5a36-11e9-9e67-30abde89489a.png)

Also put this on route, for test, but not worked
![image](https://user-images.githubusercontent.com/2231447/55761857-1bf12380-5a37-11e9-9dfa-959f3f6c23db.png)
