### ISSUE TITLE
Waiting long on verify method return

### ISSUE THREAD

**Issue by jammersonf** [ankitpokhrel/tus-php#138]
Is normal waiting log on method verify?
![image](https://user-images.githubusercontent.com/2231447/56509157-a2f4d000-64fc-11e9-8620-80b15bc2765b.png)
in a 20mb file, waiting is almost 3 min

Other question: I need to upload a 4.5gb file, is about 4hours on verify e after that, no start the upload.

Any suggestion?

**Comment by ankitpokhrel** [comment]
@jammersonf no it is not normal, fixed in this commit: https://github.com/ankitpokhrel/tus-php/commit/18ef3b94c44af1b09c1d3496bbd4ad912f5e3c0e. I am still checking if the examples can be improved further. Thank you for reporting 👍
