### ISSUE TITLE
UUID enhancement

### ISSUE THREAD

**Issue by peter279k** [ankitpokhrel/tus-php#140]
**Is your feature request related to a problem? Please describe.**

According to the `Warning` and `Caution` block in official [reference](https://www.php.net/manual/en/function.uniqid.php), the [uniqid](https://www.php.net/manual/en/function.uniqid.php) will not be 
the cryptographically secure value.

And it may be the collision value.

![image](https://user-images.githubusercontent.com/9021747/56867905-3ad34c00-6a1e-11e9-9ea9-a1f7de70bfea.png)

**Describe the solution you'd like**

I think we can implement the `UUIDv5` method or including PHP `uuid` package.

**Comment by ankitpokhrel** [comment]
@peter279k PR would be great :)
