### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Haseebfayyaz** [ankitpokhrel/tus-php#141]
catch (FileException | ClientException $e) {
            $this->create($key);
        } catch (ConnectException $e) {
         Message: syntax error, unexpected '|', expecting variable (T_VARIABLE)
i getting this error . I do not know the reson of error. Is due to php version or something I have version php 7 in my server

**Comment by ankitpokhrel** [comment]
@Haseebfayyaz this library requires PHP 7.1 or higher. Support for multiple catch was added in PHP 7.1: https://wiki.php.net/rfc/multiple-catch#implementation

**Comment by Haseebfayyaz** [comment]
thank you

**Comment by peter279k** [comment]
You can also look at the `php` minimum version requirement in [composer.json](https://github.com/ankitpokhrel/tus-php/blob/master/composer.json#L13) file.
