### ISSUE TITLE
Uppy related Predis errors

### ISSUE THREAD

**Issue by sull** [ankitpokhrel/tus-php#143]
I've installed Redis and php-redis (4.2.0-1+ubuntu16.04.1) on server. 
Setup the tus endpoint route in NGINX (/upload --> /upload.php)

uppy code:
```js
uppy.use(Uppy.Tus, {
    endpoint: 'https:/mydomain.dev/upload/',
    resume: true,
    autoRetry: true,
    retryDelays: [0, 1000, 3000, 5000]
})
```

tus endpoint code in upload.php:

```php
require __DIR__ . '/vendor/autoload.php';

$server = new \TusPhp\Tus\Server('redis');
$server
    ->setApiPath( '/upload' )
    ->setUploadDir( __DIR__ . '/uploads' )
    ->setMaxUploadSize(1000000000); // bytes

$response = $server->serve();
$response->send();

exit(0);
```

I am getting some errors:

> tus: invalid or missing Location header, originated from request (response code: 200, response text: 

> Fatal error:  Uncaught Predis\Connection\ConnectionException: Failed to parse address &amp;quot;:&amp;quot; [tcp://:] in /vendor/predis/predis/src/Connection/AbstractConnection.php:155

> /vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection-&amp;gt;onConnectionError('Failed to parse...', 0)

> /vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection-&amp;gt;createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://:', 4)

> /vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection-&amp;gt;tcpStreamInitializer(Object(Predis\Connection\Parameters))

> /vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection-&amp;gt;createResource()

> /vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection-&amp;gt;conn in /vendor/predis/predis/src/Connection/AbstractConnection.php on line 155

_I tested Predis with test code to make sure I can connect, set k/v and get value, it succeeded._

Where am I going wrong?

Using file cache works for uploads, but as it pertains to this thread, the resume resets when paused etc. Thats why I am trying with redis.

![tusphp-uppy-predis-error](https://user-images.githubusercontent.com/6834/57087013-2ff21300-6ccd-11e9-8fa2-7f685a6e1f02.gif)

**Comment by ankitpokhrel** [comment]
Fixed in #147 

Please note that:

Default redis and file configuration for server and client can be found inside `config/server.php` and `config/client.php` respectively. To override default config you can simply copy the file to your preferred location and update the parameters. You then need to set the config before doing anything else.

```php
\TusPhp\Config::set(<path to your config>);

$server = new \TusPhp\Tus\Server('redis');
```

Alternately, you can set `REDIS_HOST`, `REDIS_PORT` and `REDIS_DB` env in your server to override redis settings for both server and client.

**Comment by Nex-Coder** [comment]
Hi, sorry if replying here is a no no. Haven't contributed much to Github (yet). 

I'm getting the same issues as described here exactly. With the only exception that I'm using `file` instead of `redis`. I've tried the default config and my own. Maybe its because i'm using slim however, not experience enough to tell. Im using mostly example code just to _learn_ really.

Here is my tus routes in Slim:

Server:
```php 
$app->get('/tus-server', function(Request $request, Response $response) use ($app) {

    Config::set([
        'dir' => APP_DIR . "/testuploads/cache",
        'name' => 'tus_php.client.cache',
    ]);
    $server   = new Server();
    $response = $server->serve();
    $server->setMaxUploadSize(100000000); // 100 MB in bytes

    $response->send();

    exit(0); // Exit from current PHP process.
});
```
Client:
```php 
$app->post('/tus-upload', function(Request $request, Response $response) use ($app) {

    $client = new Client("https://".$_SERVER['SERVER_NAME']."/tus-server");

    // Alert: Sanitize all inputs properly in production code
    if ( ! empty($_FILES)) {
        $fileMeta  = $_FILES['tus_file'];
        $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

        try {
            $client->setKey($uploadKey)->file($fileMeta['tmp_name'], 'chunk_a');

            $partialKey1   = $client->getKey();

            $partialKey2   = $client->getKey();

            $partialKey3   = $client->getKey();

            $client->setFileName($fileMeta['name'])->concat($uploadKey, $partialKey2, $partialKey1, $partialKey3);

            header('Location: ' . $_SERVER['HTTP_REFERER'] . '?state=uploaded');
        } catch (ConnectionException | FileException | TusException $e) {
            header('Location: ' . $_SERVER['HTTP_REFERER'] . '?state=failed');
        }
    }
```
JS Script (Uppy):
```js
        var uppy = Uppy.Core()
            .use(Uppy.Dashboard, {
                id: 'Dashboard',
                target: '#file-span',
                inline: true,
                width: 700,
                height: 300,
                thumbnailWidth: 60,
                theme: 'dark',
            })
            .use(Uppy.Tus, {endpoint: '/tus-upload', // use your tus endpoint here
                resume: true,
                autoRetry: true,
                retryDelays: [0, 1000, 3000, 5000]})

        uppy.on('upload-success', (file, response) => {
            uppy.setFileState(file.id, { uploadURL: `${response.url}/get` })
        })
```

Is there anything im doing wrong. My Apache htaccess also contains the rewrite condition. yet i still get the same error as describe here I think:

The console.log is as follows:
> Failed to upload <file name here> tus: invalid or missing Location header, originated from request (method: POST, url: /tus-upload, response code: 200, response text: , request id: n/a)

**Comment by Nex-Coder** [comment]
Sorry, nevermind. It was due to my lack of understanding about the .htaccess and thus was requesting the wrong URL (among other things).
