### ISSUE TITLE
example help

### ISSUE THREAD

**Issue by ximengyi** [ankitpokhrel/tus-php#150]
I downloaded this library example  when  i use basic demo ,it response 'Unable to create resource'  error all the time, please help me debug this error,i use windows environment，thank you ~~

this is upload file
```php
require __DIR__ . '/../../vendor/autoload.php';

use TusPhp\Exception\TusException;
use TusPhp\Exception\FileException;
use TusPhp\Exception\ConnectionException;


$client = new \TusPhp\Tus\Client('http://bigupload.test/server.php');
$client->setApiPath('/basic/upload.php');

// Alert: Sanitize all inputs properly in production code
if ( ! empty($_FILES)) {
    $fileMeta  = $_FILES['tus_file'];
    $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

    try {

        $client->setKey($uploadKey)->file($fileMeta['tmp_name'], time() . '_' . $fileMeta['name']);

        $bytesUploaded = $client->upload(5000000); // Chunk of 5 mb

        echo json_encode([
            'status' => 'uploading',
            'bytes_uploaded' => $bytesUploaded,
            'upload_key' => $uploadKey
        ]);
    } catch (ConnectionException | FileException | TusException $e) {
        echo json_encode([
            'status' => 'error',
            'bytes_uploaded' => -1,
            'upload_key' => '',
            'error' => $e->getMessage(),
        ]);
    }
} else {
    echo json_encode([
        'status' => 'error',
        'bytes_uploaded' => -1,
        'error' => 'No input!',
    ]);
}
```
this is verify file

```php

<?php

/**
 * Sends HEAD request to figure out uploaded offset
 * if the file was uploaded partially previously.
 */

require __DIR__ . '/../../vendor/autoload.php';

use TusPhp\Exception\FileException;
use GuzzleHttp\Exception\ConnectException;

$client = new \TusPhp\Tus\Client('http://bigupload.test/server.php');

$uploadKey = uniqid('tus_file_');

try {

    $offset = $client->setKey($uploadKey)->getOffset();


    $status = false !== $offset ? 'resume' : 'new';
    $offset = false === $offset ? 0 : $offset;

    echo json_encode([
        'status' => $status,
        'bytes_uploaded' => $offset,
        'upload_key' => $uploadKey,
    ]);
} catch (ConnectException $e) {
    echo json_encode([
        'status' => 'error',
        'bytes_uploaded' => -1,
    ]);
} catch (FileException $e) {
    echo json_encode([
        'status' => 'resume',
        'bytes_uploaded' => 0,
        'upload_key' => '',
    ]);
}

```

this is nginx conf

```nginx
server {
    listen 80;
    server_name bigupload.test *.bigupload.test;
    root "C:/laragon/www/bigupload/example";
    
    index index.html index.htm index.php;
 
    location / {
	
        try_files $uri $uri/ C:/laragon/www/bigupload/example/server.php?$query_string;

    }
    
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php_upstream;		
        #fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
	
	
    charset utf-8;
	
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by ankitpokhrel** [comment]
From your nginx config it seems that your tus server endpoint is `http://bigupload.test` instead of `http://bigupload.test/server.php`.

```php
$client = new \TusPhp\Tus\Client('http://bigupload.test');
```

**Comment by ximengyi** [comment]
I have tried your suggestion, but it has not changed, still returns "{"status":"error","bytes_uploaded":-1,"upload_key":"","error":"Unable to create resource." }", I feel very confused, what other might make this error?

**Comment by ximengyi** [comment]
> From your nginx config it seems that your tus server endpoint is `http://bigupload.test` instead of `http://bigupload.test/server.php`.
> 
> ```
> $client = new \TusPhp\Tus\Client('http://bigupload.test');
> ```



> From your nginx config it seems that your tus server endpoint is `http://bigupload.test` instead of `http://bigupload.test/server.php`.
> 
> ```
> $client = new \TusPhp\Tus\Client('http://bigupload.test');
> ```

I have tried your suggestion, but it has not changed, still returns "{"status":"error","bytes_uploaded":-1,"upload_key":"","error":"Unable to create resource." }", I feel very confused, what other might make this error?

**Comment by ankitpokhrel** [comment]
@ximengyi you can get full error trace by commenting catch statements in above methods. Also check your server log to find any clue on the error. Looking at the error I can only say that there is some permission issue in the uploads dir.

**Comment by ximengyi** [comment]
Thank you, I have run successfully, as you said, this is the problem of folder permissions. I moved the environment to linux, I found the error log, windows did not prompt, prompted under linux, I put the relevant files The folder permissions are set to 777, it works, hahaha, thank you very much~

**Comment by huyiwinner** [comment]
Which folders need to be reset permissions under Linux?
