### ISSUE TITLE
tus-example of uppy work perfacly on localhost but not on apache server

### ISSUE THREAD

**Issue by janakpuri** [ankitpokhrel/tus-php#153]
**Actually this is not bug or enhancement. I am posting here because I cant find proper documentation to understand some issues I have.**

I am working on a project to upload large size(max 20gb) videos to server. 
I have implemented your partial upload example.
And I am getting "Oops! Something went wrong. Please try again!".

I tried to debug the error and it lead me to the client.php file (src file).
Basically this happening because of 200 passed in $statusCode.

I am trying to figure out the problem. 
Some of the points I have in mind that are causing the trouble.
1. Where to place server.php ?
2. What is mandatory to included inside server.php file ?
3. I wanna know about "Tus Endpoint" 
4. How can I upload file to my desired location

my File path is same as yours - "http://localhost/tus-php/example/partial/"

Thanks in advance. @ankitpokhrel

**Comment by samundra** [comment]
@janakpuri It's interesting that you're trying to upload 20GB of file. 

I have 2 questions mentioned below:

1. Did you try to pull this repository and then tried uploading 20GB of file upload?
2. Did you setup your local TUS Server and then tried uploading there?

After that we can begin to dig more.

**Comment by janakpuri** [comment]
hey @samundra 

I am running on local TUS server and tried uploading it.

**Comment by samundra** [comment]
Can you please explain us how you came to the conclusion that `Basically this happening because of 200 passed in $statusCode.`? 

Also, I would suggest you to try 20GB upload on repository code without any custom changes to make sure that it works/breaks without changes.

**Comment by janakpuri** [comment]
Earlier when file was not uploading, I thought some important parameter might not be passing via POST request. So, I tried to echo errors and that lead me to Client.php file (located here - "tus-php/src/Tus/Client.php")

In client.php file, 

`    public function create(string $key) : string
    {
        $headers = [
            'Upload-Length' => $this->fileSize,
            'Upload-Key' => $key,
            'Upload-Checksum' => $this->getUploadChecksumHeader(),
            'Upload-Metadata' => 'filename ' . base64_encode($this->fileName),
        ];
        if ($this->isPartial()) {
            $headers += ['Upload-Concat' => 'partial'];
        }

        $response = $this->getClient()->post($this->apiPath, [
            'headers' => $headers,
        ]);

        $statusCode = $response->getStatusCode();  // **Here $statusCode it gets status code** 
        
        // echo "<pre>";
        // print_r($statusCode);
        // exit();

       //**if condition to check status code is 201 or not,** 
       //**in my case status code 200 is passed.**
        if (HttpResponse::HTTP_CREATED !== $statusCode) {
            throw new FileException('Unable to create resource.');
        }

        $uploadLocation = current($response->getHeader('location'));

        $this->getCache()->set($this->getKey(), [
            'location' => $uploadLocation,
            'expires_at' => Carbon::now()->addSeconds($this->getCache()->getTtl())->format($this->getCache()::RFC_7231),
        ]);

        return $uploadLocation;
    }`

I guess this might issue of folder permission.
I am gonna try it again tonight with your suggestion.

Thanks @samundra.

**Comment by axay97** [comment]
hey @janakpuri @samundra @ankitpokhrel 
I am posting here because I am also confused about the **server.php file,** **endpoint** and **upload path.** 

1. Where to place server.php?
2. What is endpoint and what it contains?
3. Where will be file uploaded using your example/basic or example/partial folder for reference?

I am using it on Windows 8 with xampp which has PHP 7.3 version.

Also, I am getting an error that **Unable to create resource**

How to resolve this error?

**Comment by janakpuri** [comment]
hey @samundra,

**Also, I would suggest you to try 20GB upload on repository code without any custom changes to make sure that it works/breaks without changes.**

I have tried as you suggested But I am getting same error as @axay97 has defined.

**Unable to create resource**

I am unsure what causes that error. Guide me through this error.

**Comment by axay97** [comment]
hey @janakpuri I suggest you to use uppy example from example folder.

**Please note that create "uploads" folder in tus-php directory and you might also wanna remove "redis" from server.php file.**

**And set your endpoint like - "https://myurl.com/tus-php/example/server.php"**

**Another thing which might cause this error is "require '/../../vendor/autoload.php'  " 
Make sure You have vendor folder in correct directory. and if you dont have it - this might be causing the error. Go and run composer and download all dependency.**


Hope this helps. 

Have a good day.

**Comment by janakpuri** [comment]
Thanks @axay97 
Your suggestion really worked. 
I figured the problem was that I was setting endpoint as "http://myurl.com/example" which was not working.
So i changed it to "http://myurl.com/example/server.php" and videos started uploading.
Meanwhile It works totally fine on localhost. 
But I am facing problem testing it on live server.
When I upload file larger than 500MB, it responds with net::ERR_SPDY_PROTOCOL_ERROR
and Sometimes it shows net::ERR_CONNECTION_RESET

Another thing is this demo works fine with chrome but it doesn't work on firefox.
here is the link "https://khodiyarplastic.tk/example/uppy/"

Do you know about this ? @ankitpokhrel @samundra @fidelix

**Comment by janakpuri** [comment]
tus example of uppy work perfacly on localhost but not on apache server
I am also having the same problem as yours @axay97.
However it was working well on local server But as i moved my code to live apache server it seem to be not working on larger files.
It started giving error when i upload 1 gb file.
Size of file was 1GB.
max_upload size is 40 GB in php.ini file 

here is the error -
`PATCH https://mydomain.com/tus/example/server.php/files/84ad1dd2-b1fc-484c-a100-541d6b133950 net::ERR_CONNECTION_RESET`

I cant reach to conclusion what is causing the error.

@samundra @account

**Comment by ankitpokhrel** [comment]
Hi @janakpuri , apologies for late response. Did you manage to sort out the issue or need any further help?

**Comment by janakpuri** [comment]
hi @ankitpokhrel, apologies for late response.

I have managed to sort out this issue.
I do have another issue, But I think That is way different than this one. So, I am closing this issue.

Thanks you all.
@ankitpokhrel @samundra @axay97 @fidelix

**Comment by samundra** [comment]
@janakpuri Can you please open another ticket for another issue that you are talking about? That would be helpful to keep track of issues. 

And perhaps post the solution as well for the issue you had. It will serve as future reference for those who may encounter same issue like yours.

**Comment by Carlos-Costa** [comment]
> tus example of uppy work perfacly on localhost but not on apache server
> I am also having the same problem as yours @axay97.
> However it was working well on local server But as i moved my code to live apache server it seem to be not working on larger files.
> It started giving error when i upload 1 gb file.
> Size of file was 1GB.
> max_upload size is 40 GB in php.ini file
> 
> here is the error -
> `PATCH https://mydomain.com/tus/example/server.php/files/84ad1dd2-b1fc-484c-a100-541d6b133950 net::ERR_CONNECTION_RESET`
> 
> I cant reach to conclusion what is causing the error.
> 
> @samundra

Hi... How did you Solve this?

Thanks
