### ISSUE TITLE
Basic installation failed ("But I followed the recipe!?")

### ISSUE THREAD

**Issue by HankBrown** [ankitpokhrel/tus-php#155]
**Describe the bug**

Basic installation failure.

**To Reproduce**

```
$ git clone https://github.com/ankitpokhrel/tus-php.git ./tusphp
Cloning into './tusphp'...
remote: Enumerating objects: 1242, done.
remote: Total 1242 (delta 0), reused 0 (delta 0), pack-reused 1242
Receiving objects: 100% (1242/1242), 16.01 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (794/794), done.

$ cd tusphp
$ composer require ankitpokhrel/tus-php
Using version ^1.0 for ankitpokhrel/tus-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: ankitpokhrel/tus-php[v1.0.0, dev-master].
    - Can only install one of: ankitpokhrel/tus-php[v1.0.4, dev-master].
    - Can only install one of: ankitpokhrel/tus-php[v1.0.5, dev-master].
    - Installation request for ankitpokhrel/tus-php dev-master -> satisfiable by ankitpokhrel/tus-php[dev-master].
    - Installation request for ankitpokhrel/tus-php ^1.0 -> satisfiable by ankitpokhrel/tus-php[v1.0.0, v1.0.4, v1.0.5].

Installation failed, reverting ./composer.json to its original content.

```

**Expected behavior**

No error messages.

**Screenshots**

None

**Additional context**

I suspect  the message is telling me how to fix it, that this issue is really my own ignorance with composer.  But when it try various arguments for composer, I find no joy.

Curiously, the composer command works from an empty folder.
I copy that into my working folder, now have composer files and vendor dir.
But fail to run. Might be another problem on my end, but this installation process has left me uncertain of whether/how to pursue it.

Thank you for your time and any advice.

**Comment by ankitpokhrel** [comment]
@HankBrown you are cloning and then trying to install the same package via composer. I think you meant to do `composer install` after `cd tusphp` step, instead of require.

**Comment by HankBrown** [comment]
You are correct.
Argh. I have a dual php system and had not used composer with 7.2
That may have added to my confusion...
I _think_ php 7+ is a requirement.
