### ISSUE TITLE
400 Bad Request error - Laravel

### ISSUE THREAD

**Issue by georgewritescode** [ankitpokhrel/tus-php#156]
Hi,
When implementing this library into my laravel app with the https://github.com/tus/tus-js-client library I am receiving a 400 Bad Request error. 

I have tried this in two server environments, docker and a vagrant box, and am receiving the same error with both. 

I can var_dump until ```$response->send();``` and so it seems the request is hitting the code fine and it is running until that send function.

Do you have any idea what might be causing this error?

Thanks!
George

Supporting Info:

PHP code in my web.php routes file:
```
Route::any('/tus/{any?}', function () {

    \TusPhp\Config::set(config_path('tus-server.php'));

    $server = new \TusPhp\Tus\Server('redis');

    $server
        ->setApiPath('/tus') // tus server endpoint.
        ->setUploadDir(storage_path('app/public/teams')); // uploads dir.
    $response = $server->serve();

    return $response->send();

})->where('any', '.*');
```

When looking in Chrome at the failed request in devtools it gives me this information:
General
```
Request URL: https://app.laravel.test/tus
Request Method: POST
Status Code: 400 
Remote Address: 192.168.10.10:443
Referrer Policy: no-referrer-when-downgrade
```
Response
```
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Content-Length, Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Tus-Version, Tus-Resumable, Upload-Metadata
access-control-allow-methods: GET,POST,PATCH,DELETE,HEAD,OPTIONS
access-control-allow-origin: https://app.laravel.test
access-control-expose-headers: Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Version, Tus-Resumable, Tus-Extension, Location
access-control-max-age: 86400
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Mon, 27 May 2019 12:17:02 GMT
server: nginx/1.13.3
status: 400
tus-resumable: 1.0.0
x-content-type-options: nosniff
```
Request
```
Origin: https://app.laravel.test
Referer: https://app.laravel.test/page
Tus-Resumable: 1.0.0
Upload-Length: 4038903
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
```

Notes:
1. I have tried it with the laravel service provider way as per the readme/docs.
2. I have added '/tus', '/tus/*', to the csrf exceptions array.
3. I have tried it using the file system cache instead of redis
4. I have write permissions on the storage folder
5. Laravel is set up with the APP_URL to use the https://app.laravel.test domain and all other routes in the application work fine. 

JS upload code:
```
var upload = new tus.Upload(file, {
            endpoint: "/tus",
            retryDelays: [0, 3000, 5000, 10000, 20000]
        })
upload.start()
```

**Comment by ankitpokhrel** [comment]
@georgewritescode are you able to access all tus endpoints using curl or any other http or tus client?

**Comment by georgewritescode** [comment]
Hi @ankitpokhrel ,
Thanks for your response.

I solved this by adding a metadata property to the tus-js-client with the fileName and fileType properties within it.

If you like I can add a tus-js-client example to the readme.

Thanks,
George

**Comment by ankitpokhrel** [comment]
> If you like I can add a tus-js-client example to the readme.

That would be great :)

**Comment by georgewritescode** [comment]
Done. Thanks for accepting the PR.

All the best

**Comment by MohammadNasirAriaee** [comment]
Please, can anyone help, when I try to read json file like this using javascript ($.getJSON('/extras/contract_types.json', function (result) {...})
it returns 400 bad request in console but before it was working correctly.
Any idea for solving this error, thanks.
