### ISSUE TITLE
 Redis cache time suggestion

### ISSUE THREAD

**Issue by ximengyi** [ankitpokhrel/tus-php#160]
I found that the uploaded file information is permanently stored in redis. I think this code is about 72 lines in TusPhp\Cache\RedisStore.
 $status = $this->redis->set($this->getPrefix() . $key, json_encode($contents))
This may be more appropriate

 $status = $this->redis->set($this->getPrefix() . $key, json_encode($contents),'EX',$this->getTtl());

**Comment by ankitpokhrel** [comment]
@ximengyi this design decision is actually on purpose. We will not have any record of expired uploads if we set ttl at this point. You need to run [expiration script](https://github.com/ankitpokhrel/tus-php#expiration) in your server, periodically, to cleanup expired and unfinished files. This will cleanup your redis cache as well.
