### ISSUE TITLE
Grabbing upload URIs from tus-server.upload.created event listener

### ISSUE THREAD

**Issue by Poldovico** [ankitpokhrel/tus-php#162]
I need to grab the URIs of new uploads on the server side to save it in a database, which I am trying to do by listening for the `tus-server.upload.created` event and grabbing it out of the response's Location header.  
I am expecting this code to work:  
```php
public function myTusEndpoint() {
  $myTusPhpServer->event()->addListener('tus-server.upload.created',
    function (\TusPhp\Events\TusEvent $event) use ($currentUser) {
      $response = $event->getResponse();
      $headers = $response->getHeaders();
      // save $headers['Location'] in the database
    }
  );
  $tusResponse = $myTusPhpServer->serve();
  $tusResponse->send();
}
```
But instead I just get NULL in my DB.  
I tried printing $headers as json and it looks like this: 
```json
{
  "X-Content-Type-Options": "nosniff",
  "Tus-Resumable": "1.0.0",
  "Access-Control-Allow-Origin": null,
  "Access-Control-Allow-Methods": "GET,POST,PATCH,DELETE,HEAD,OPTIONS",
  "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Content-Length, Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Tus-Version, Tus-Resumable, Upload-Metadata",
  "Access-Control-Expose-Headers": "Upload-Key, Upload-Checksum, Upload-Length, Upload-Offset, Upload-Metadata, Tus-Version, Tus-Resumable, Tus-Extension, Location",
  "Access-Control-Max-Age": 86400
}
```
Which is nothing like what I get in the actual response to my POST requests to this endpoint, so I am confused as to what I am actually pulling when I call `$event->getResponse()`.  
What am I doing wrong? How can I get the URI of a new upload?

**Comment by Poldovico** [comment]
Ok, I just realised getUploadKey() exists.  
That said, I am still curious why the headers I was messing with were different than the ones I was actually receiving.

**Comment by ankitpokhrel** [comment]
Hi @Poldovico  looks like `Location` and `Upload-Expires` headers are set after sending the event, that is why you are not able to see those headers in response: https://github.com/ankitpokhrel/tus-php/blob/master/src/Tus/Server.php#L380-L391

**Comment by jonesdev** [comment]
Hi @ankitpokhrel

What would be a good way to go about fixing this issue?

Dispatching the event with the location and upload expires header set?

**Comment by ankitpokhrel** [comment]
@jonesdev yes, we first need to set the response headers, dispatch the event and then send the response.

**Comment by jonesdev** [comment]
@ankitpokhrel 

Hey - 
![image](https://user-images.githubusercontent.com/36740276/66195973-aa193000-e68f-11e9-89b8-85a488a9a449.png)

Diff provided above; would this be acceptable? I'm unsure on how to test this (functionality wise) so would like to verify beforehand.

**Comment by ankitpokhrel** [comment]
You are passing [third argument to event dispatcher](https://github.com/symfony/event-dispatcher/blob/master/EventDispatcher.php#L49) which doesn't exist. You need to add headers to the tus response before passing it down to `UploadCreated` event.

Not tested but it should be something like this.
```diff
+        $headers  = [
+            'Location' => $location,
+            'Upload-Expires' => $this->cache->get($uploadKey)['expires_at'],
+        ];
+
         $this->event()->dispatch(
             UploadCreated::NAME,
-            new UploadCreated($file, $this->getRequest(), $this->getResponse())
+            new UploadCreated($file, $this->getRequest(), $this->getResponse()->setHeaders($headers))
         );

-        return $this->response->send(
-            null,
-            HttpResponse::HTTP_CREATED,
-            [
-                'Location' => $location,
-                'Upload-Expires' => $this->cache->get($uploadKey)['expires_at'],
-            ]
-        );
+        return $this->response->send(null, HttpResponse::HTTP_CREATED, $headers);
```

**Comment by jonesdev** [comment]
@ankitpokhrel 

Totally forgot about checking the function for which or how many args it takes - my bad.

I'll look at implementing your suggestion and correcting any unit tests that may need to be corrected.

Thank you.
