### ISSUE TITLE
Save user sent meta data

### ISSUE THREAD

**Issue by alucic** [ankitpokhrel/tus-php#163]
I would like to be able to store additional information. Once the file is created, any meta data that's passed by the client should be stored.

Example:
https://uppy.io/docs/uppy/#meta

As a user I'd like to read file meta and user set meta using `$event->getFile()->details();`

This would be helpful for issues like this one https://github.com/ankitpokhrel/tus-php/issues/124

Go implementation is storing user meta data together with TUS related info
https://github.com/tus/tusd/blob/d23be46d7a236714c451601f87fe6bbab7776d45/unrouted_handler.go#L290-L299

If this makes sense I can come up with an implementation and we can discuss details in the PR

**Comment by ankitpokhrel** [comment]
I think this will be a good enhancement. We would be happy to review and discuss the solution if you can send a PR.
