### ISSUE TITLE
Downloading a file causes a notice / Drop iconv dependency

### ISSUE THREAD

**Issue by Steveb-p** [ankitpokhrel/tus-php#165]
**Describe the bug**
Attempting to download previously uploaded file using `files/{token}/get` causes a notice: 
`Notice: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT' is not allowed`
which originates from 
https://github.com/ankitpokhrel/tus-php/blob/3878a4933d9e62d4e9a543e88d2b76fd4787d0e1/src/Response.php#L137

**To Reproduce**
1. Upload a file (for example using `/files/{token}` endpoint)
2. Try to download the file (`GET /files/{token}/get`)

**Additional context**
The `Response` object in Symfony 3.4.11 (which is the lowest allowed by composer declaration) already contains instructions regarding filename fallback, so from my point of view the code generating fallback name can probably be omitted.
https://github.com/symfony/http-foundation/blob/a7b5fc605d1c215cea1122359044b1e682eb70c0/BinaryFileResponse.php#L156-L174

On a side note, I've noticed that Uppy generates link without `/get` suffix and there is a `HEAD`/`GET` specific code that states:
```
    /** 
     * As per RFC7231, we need to treat HEAD and GET as an identical request.
     * All major PHP frameworks follows the same and silently transforms each
     * HEAD requests to GET.
     */
```
Is this request handling that always treats direct requests to `/files/{token}` as HEAD requests still intended?

**Comment by ankitpokhrel** [comment]
> Notice: iconv(): Wrong charset, conversion from UTF-8' to ASCII//TRANSLIT' is not allowed

Most probably this is the issue with `iconv` extension not being configured properly in your php installation. But, anyway, it seems we can drop the dependency with `iconv` extension since `symfony` is already handling it internally as you mentioned.

> Is this request handling that always treats direct requests to /files/{token} as HEAD requests still intended?

Yes, it is intended and I believe you can modify `Uppy` link to add `/get` at the end of the URL.

**Comment by Steveb-p** [comment]
@ankitpokhrel Thanks, I did stumble upon this in the past and didn't realize it's basically related to alpine docker having a different library (plenty of references to it actually). I've adjusted issue name to better reflect what is the expected course of action.
