### ISSUE TITLE
Allow manipulation of File before saving

### ISSUE THREAD

**Issue by Steveb-p** [ankitpokhrel/tus-php#172]
**Is your feature request related to a problem? Please describe.**
Changing for example file name during `tus-server.upload.created` requires manipulation of cache instance, causing an additional read/write to it.

**Describe the solution you'd like**
`tus-server.upload.created` event could be moved before cache is saved or an additional event could be dispatched before it (if we're considering cache as a de-facto database)

**Describe alternatives you've considered**

**Additional context**
Original comment from #167.

@ankitpokhrel could we move the emission of `tus-server.upload.created` event before cache is saved? That way there would be no need to manipulate cache in any way, and I don't see any mutation of `File` object from cache saving. All that would need to be done to change filename could be done from inside the event handler interacting with `File` object.

https://github.com/ankitpokhrel/tus-php/blob/66f635531677606ac41d222b764e32f343ab9b11/src/Tus/Server.php#L370-L383

...would be instead...

```php
$file = $this->buildFile([
    'name' => $fileName,
    'offset' => 0,
    'size' => $this->getRequest()->header('Upload-Length'),
    'file_path' => $filePath,
    'location' => $location,
])->setKey($uploadKey)->setChecksum($checksum);
$this->event()->dispatch(
    UploadCreated::NAME,
    new UploadCreated($file, $this->getRequest(), $this->getResponse())
);
$this->cache->set($uploadKey, $file->details() + ['upload_type' => $uploadType]);
```

EDIT: Or, create `tus-server.upload.pre_created` event, so one can be sure that `File` was "persisted" completely?

**Comment by ankitpokhrel** [comment]
@Steveb-p `$fileName` is passed down the chain in that method, for eg `$fileName` is used to build file path:
https://github.com/ankitpokhrel/tus-php/blob/a9c9d954889c6eb1848426aa891cae6535449c65/src/Tus/Server.php#L356

This means that there will be side effects if we change the file name later in the process. User will have to modify file path along with the file name, which is bit odd. I would still argue to use direct cache manipulation unless we have some solution without these side effects.

**Comment by Steveb-p** [comment]
@ankitpokhrel You're right, it would cause a side effect and would break following operations :/ I'll give it another thought later.

**Comment by Poldovico** [comment]
Could editing the filename not be handled by a middleware?

**Comment by Steveb-p** [comment]
> Could editing the filename not be handled by a middleware?

If it would manipulate filename header on each request then yes. This would be necessary because then tus-php reads where file should be written based on this (unless I'm mistaken).

Tus protocol does not specify how filename should be passed to the server.
https://tus.io/protocols/resumable-upload.html#how-can-i-get-the-file-name-or-file-type-for-an-upload

> For itself, the tus protocol does not have a direct mechanism to obtain the type or filename of an upload as the specification does not have the principle of a disk-based file, allowing you to upload arbitrary data using tus. However, the wanted functionality can be achieved by utilizing metadata. A Client can attach the file’s name and type to an upload when it’s being created by setting the Upload-Metadata header. On the other side, the Server can read these values and determine the name and type of the upload.
