### ISSUE TITLE
Multiple instances on one redis service

### ISSUE THREAD

**Issue by MichalKrakow** [ankitpokhrel/tus-php#175]
I found it to impossible to set cache prefix which allows for only one instance of Tus running on one server. The ability to modify cache key prefix would allow for using multiple Tus server instances with single redis service running

**Comment by ankitpokhrel** [comment]
You can configure cache during server initialization.

```php
$redis = new \TusPhp\Cache\RedisStore([
    // Connection parameters.
]);

$redis->setPrefix('cache_prefix_');

$server = new \TusPhp\Tus\Server($redis);
```

**Comment by MichalKrakow** [comment]
Nice, 
how would you acomodate it to Laravel integration scheme?

**Comment by MichalKrakow** [comment]
I've tried changing the TusServiceProvider with:
```
$redis = new \TusPhp\Cache\RedisStore();
$redis->setPrefix(env('APP_NAME') . ":tus");
$server = new TusServer($redis);
```
But no luk there. Still it uses it's own key pattern.

I've noticed that second app running on the same server uses redis with index 2 **tus2:className** but i cant find why that's the case.

**Comment by ankitpokhrel** [comment]
@MichalKrakow can you please let us know how can we reproduce this issue? Clear steps on what you did, what was expected and what you got instead would be helpful.
