### ISSUE TITLE
Facilitate null-coalescing the return values of TusRequest::extractMeta()

### ISSUE THREAD

**Issue by Poldovico** [ankitpokhrel/tus-php#177]
**Is your feature request related to a problem? Please describe.**
I find myself needing to fall back to alternative values in case a metadata field is not set. I also believe null is a more appropriate value to describe unset fields, and this behaviour would be coherent with that of Request::extractAllMetadata().

**Describe the solution you'd like**
I would like the Request::extractMeta() method to return null for unset fields, so that I may use the null-coalesce (??) operator to clearly and concisely implement my desired behaviour. This would be as simple as changing the final `return '';` statement to `return null;` in the method definition, though I do not know whether this would affect the behaviour of other tus-php code.

**Describe alternatives you've considered**
I can just test for an empty string with conditionals. This becomes verbose and less clear in the case of multiple fallbacks, but it does work perfectly.

**Additional context**
That's pretty much it.

**Comment by samundra** [comment]
I don'tthink it's a good idea to change the mixed return type. The current return type is string and is consistent to what it needs to be. 

@Poldovico Like you have mentioned, solution would be to nullify empty string and create a utility wrapper method for it which we can implement in application level. The change necessarily do not need to be done on tus-php itself. Thus, I am closing this issue as we already have solution that do not require change in tus-php itself.
