### ISSUE TITLE
Retrieve metatadata in tus-server.upload.complete event

### ISSUE THREAD

**Issue by darthf1** [ankitpokhrel/tus-php#183]
Hi,

I want to add logic after a file has been uploaded completely, for which i need some metadata. I'm missing the `Upload-Metadata` header data during the `tus-server.upload.complete` event. It is available in the `tus-server.upload.created` event.

Is it possible to get the `Upload-Metadata` information in the `tus-server.upload.complete` event? I'm using Symfony and couldn't find the header in the Symfony Request either.

Edit: resolved it for now via a header.

**Comment by ankitpokhrel** [comment]
Ping @DrudgeRajen

**Comment by DrudgeRajen** [comment]
HI @darthf1 Can you please share your implementation?

**Comment by ankitpokhrel** [comment]
Just tried this, upload metadata are available in both created and complete event. 

@darthf1 please provide more information if you are still having issues.
