### ISSUE TITLE
Duplicate response when upload

### ISSUE THREAD

**Issue by silver247** [ankitpokhrel/tus-php#186]
Hi, I've use tus-php integration with Laravel + uppy, it seem work without any problem but there is one thing that I've found that tus server always response with duplicate header, how can I fix it or this is normal?

btw I've attached screenshots downthere.

POST : ![1](https://user-images.githubusercontent.com/4065129/65004133-8cc13380-d925-11e9-82dc-749b019a1da4.PNG)
PATCH  : ![2](https://user-images.githubusercontent.com/4065129/65004135-8cc13380-d925-11e9-86b6-e5502bbc24db.PNG)

This is environment I use.

1. Windows OS + Xampp
2. Laravel 6.0
3. Uppy
4. file base cache in tus  server (since I cannot use redis anyways)

Thanks in advance.

**Comment by ankitpokhrel** [comment]
No that is not normal. Can you provide steps on how did you setup your server in laravel?

**Comment by ankitpokhrel** [comment]
Ping @DrudgeRajen

**Comment by silver247** [comment]
Thanks for replying

I've set up by using your wiki [via this link]( https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration )
Here is my TusServiceProvider.php
![1](https://user-images.githubusercontent.com/4065129/65382486-b072e800-dd30-11e9-8fa5-3d5a8d59c96f.JPG)
Ps. since I've dev in windows environment, so I used file system cache instead redis.

By the way, there is one more question I'd like to ask is it possible to send other custom response data to uppy besides uploadUrl?

**Comment by DrudgeRajen** [comment]
@silver247 I tried with laravel 6.0 and uppy but I am not able to reproduce the issue. Can you please share some more details?

**Comment by silver247** [comment]
Thanks for replying

I'm not sure if it useful information but everytime I use tus with uppy, before POST method fired the request will send HEAD method and always return 404 (in case of new file) and it also has duplicate response header too (attach image below)
![3](https://user-images.githubusercontent.com/4065129/65473206-f6e75480-dea0-11e9-9837-4d0a48287c91.PNG)

By the way, can you share your tus's and uppy set up? I'll try to follow your step and see if this issue occur.

**Comment by DrudgeRajen** [comment]
I follow the same documenation.

AppServiceProvider.php
```
 $this->app->singleton('tus-server', function ($app) {
            $server = new TusServer();

            $server->setApiPath('/tus') // tus server endpoint.
                ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.

            $server->event()->addListener('tus-server.upload.complete', function (\TusPhp\Events\TusEvent $event) {
                $fileMeta = $event->getFile()->details();
                $request  = $event->getRequest();
                $response = $event->getResponse();
            });
            $server->event()->addListener('tus-server.upload.created', function (\TusPhp\Events\TusEvent $event) {
                $fileMeta = $event->getFile()->details();
                $request  = $event->getRequest();
                $response = $event->getResponse();
            });

            return $server;
        });
```

web.php
```
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();

    return $response->send();
})->where('any', '.*');
```
uppy
```
    const uppy = Uppy.Core()
    uppy.use(Uppy.Dashboard, { target: '#drag-drop-area', inline: true, height: 450 })
    uppy.use(Uppy.Webcam, { target: Uppy.Dashboard })
    uppy.use(Uppy.Tus, { endpoint: 'http://localhost:9191/tus/' })
```

**Comment by silver247** [comment]
I have some update about this issue, When I deploy to cloud server (I use AWS) it work perfectly and this issue didn't occur. My assumption is this issue might occured from specific environment because I test with 2 computer and this issue still same.

Here is mine
1. Windows 10
2. Xampp version 7.2.7
3. PHP version 7.2.7
4. Laravel 6.0
4. Tus file base cache.

**Comment by DrudgeRajen** [comment]
Glad to know that it is working on your server without any problem.  I tried to replicate the issue on Linux environment, with

1) Ubuntu 18.04
2) PHP  7.2
3) Laravel 6.0
4) Nginx
5) Tus file base cache. 

I will try with same as of your environment and let's see if I can replicate. I think it is good to find the issue and fix it so that others will not have to suffer from it ;). Will let you know the output ASAP.

**Comment by XartIrok** [comment]
Hi, i have the same problem i think it could be Windows, my main setup is different and i have duplicate header.

1. Windows + WAMP.NET
2. PHP7.2 + Nginx
3. Symfony 4.3
4. React + tus-js-client
5. file cache

**Comment by kohenkatz** [comment]
In case anyone else finds this, I had this problem too, and here's what fixed it:

Change the route to this:

```
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();

    return $response;
})->where('any', '.*');
```

(All I did was get rid of `->send()` from the `return` line.

This allows Laravel to handle converting the Symfony response into a Laravel response, instead of trying to send the Symfony response directly.

I am not yet sure why it works without this change on some machines but others need it. It may be related to some PHP configuration, but I don't have time now to figure out what.
