### ISSUE TITLE
Enable native function invocation

### ISSUE THREAD

**Issue by ankitpokhrel** [ankitpokhrel/tus-php#190]
Since PHP 7.0, some functions are replaced by opcodes, producing much faster code. Functions like [these](https://github.com/php/php-src/blob/f2db305fa4e9bd7d04d567822687ec714aedcdb5/Zend/zend_compile.c#L3872) and [these](https://github.com/php/php-src/blob/master/ext/opcache/Optimizer/pass1_5.c#L335-L338) can be referenced with root namespace `\` before function invocation to speed up resolving.

We can use [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) `native_function_invocation` option for this.

```bash
php-cs-fixer fix src/ --rules=native_function_invocation --allow-risky=yes
```

**Comment by jonesdev** [comment]
I would like to attempt this issue.

I'll take a look now and submit a PR if it goes well.

**Comment by ankitpokhrel** [comment]
Done in #193
