### ISSUE TITLE
Ensure that redis is only listening on docker network, not publicly

### ISSUE THREAD

**Issue by bluepuma77** [ankitpokhrel/tus-php#211]
**Describe the bug**
When starting tus-php with bin/docker.sh, it starts the redis container attached to the external network interface, not just the internal docker network.

**To Reproduce**
```
# bin/docker.sh
...
# docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
b521bdb1ee0e        tus-php_tus-server   "entrypoint.sh"          8 minutes ago       Up 8 minutes        0.0.0.0:8081->80/tcp     tus-php-server
003a7cbfd043        redis                "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:6379->6379/tcp   tus-php-redis
1e57dc2bbcee        tus-php_tus-client   "sh /sbin/runit-wrap…"   8 minutes ago       Up 8 minutes        0.0.0.0:8080->80/tcp     tus-php-client
```

**Expected behavior**
Redis should only be available on docker network, not external.

**Additional context**
Received warning email from "Federal Office for Information Security (BSI)" about this, you should not leave redis open on the Internet.

**Comment by samundra** [comment]
Hi @bluepuma77 

The current setup of docker is supposed to be used for development only. It's not meant to be used in production (sorry if this has not been mentioned before).

However, It's a good practice to link containers internally and not exposed to publicly. Thank you for bringing this to our attention. We'll update it soon. If you could send a PR that would be most welcome, as it can take time for us. 

In any case, would it be possible for you to send us detail regarding email that you received as warning. It would help us to isolate the scope for the issue. 

Thank you,
Samundra
