### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by darthf1** [ankitpokhrel/tus-php#214]
Hi,

If i'm correct I didn't see any ticket or PR already on this topic. Is it possible to provide Symfony 5 support? Is it just an update of `composer.json` or does it need more work?

**Comment by ankitpokhrel** [comment]
@darthf1 Hopefully it will work just by updating `composer.json`. Feel free to test and create a PR :)

**Comment by ankitpokhrel** [comment]
@darthf1 please use symfony-5 branch for Symfony 5 support.

```bash
composer require ankitpokhrel/tus-php:dev-symfony-5
```

**Comment by darthf1** [comment]
Seems to be it! Did an install, uploaded some files and saw nothing (wrong) in the console and/or logs.

Thanks for creating the branch.
