### ISSUE TITLE
How the Concatenation works while connect aws S3? 

### ISSUE THREAD

**Issue by alameenlr** [ankitpokhrel/tus-php#216]
How the Concatenation works?

Is it like this.?
```
Step 1: Download previous content Stream
Step 2: New content Stream = Previous content Stream+Current Content Stream
Step 3: Upload New content Stream
```

**Comment by ankitpokhrel** [comment]
`tus-php` doesn't directly support concatenation for S3. You can either, upload files in your server first (in chunks), concatenate and then send the full file to S3. Or, download previous content, append and upload new content like you mentioned.
