### ISSUE TITLE
How can bind tus-php events inside Laravel Framework

### ISSUE THREAD

**Issue by adri21112** [ankitpokhrel/tus-php#218]
Hi.

I am working to rename the files upload with the tus-php server. Following the [issue-167](https://github.com/ankitpokhrel/tus-php/issues/167), I am trying to subscribe to the tus-server.upload.created inside a laravel listener and rename tie file but I don't know if it is possible.

Somebody can offer some tips?

Thanks!

**Comment by ankitpokhrel** [comment]
@adri21112 if you are using `tus-php` client, then you can pass the required name in [->file](https://github.com/ankitpokhrel/tus-php/blob/master/src/Tus/Client.php#L83) method.

If you want to rename it in server-side, better would be to listen to `tus-server.upload.complete` event which gets fired after the upload is fully done. You will get the file object which contains file path of that upload and you can rename it there.
