### ISSUE TITLE
Empty result on file access/download

### ISSUE THREAD

**Issue by myscienceisbetter** [ankitpokhrel/tus-php#219]
I'm using the tus-js-client to upload some files on the server and everything works fine, the file get uploaded.

However, when I'm trying to access/download a file that was just uploaded on the server (i've checked and the file is there), however an empty page shows up in browser. I'm using the url returned by .url property in the response: https://<my-domain-bame>/server.php/files/1e02ef98-09fc-4c5f-94f4-700652a8f87d. Note that the GET returns a Status Code: 200.

I'm running Apache 2.4 with HTTP2, PHP 7.3, redis cache

Here is the apache log:
<my-IP-here> - - [06/Dec/2019:04:33:12 -0500] "GET /server.php/files/1e02ef98-09fc-4c5f-94f4-700652a8f87d HTTP/2.0" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:71.0) Gecko/20100101 Firefox/71.0"

And the redis-cli monitor entry:
1575624884.590250 [0 127.0.0.1:37336] "SELECT" "0"
1575624884.590704 [0 127.0.0.1:37336] "GET" "tus:server:1e02ef98-09fc-4c5f-94f4-700652a8f87d"

My .htaccess file:
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^files/?(.*)?$ /server.php?$1 [QSA,L]

<IfModule mime_module>
  AddHandler application/x-httpd-ea-php73 .php .php7 .phtml
</IfModule>

**Comment by ankitpokhrel** [comment]
@myscienceisbetter you need to use `GET /files/<key>/get` to download the file. This was done since we need to treat HEAD and GET as an identical request as per [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.2). File download in `GET /files/<key>` request is not a part of the tus specification.

**Comment by myscienceisbetter** [comment]
Thanks, this seems to be doing the trick!
