### ISSUE TITLE
Cannot download file from S3 because finfo / mime_content_type is not supported by remote streams

### ISSUE THREAD

**Issue by pgrzesiecki** [ankitpokhrel/tus-php#223]
Hi.
I've noticed problem with files uploaded do S3. Upload works perfect even with chunks but there is no possbility to download uploaded file by tus-php library. Problem appears because **finfo** / **mime_content_type** don't appear to support remote streams and works only with local files.

The error that appears: **Warning: finfo::file(): Failed identify data 0:invalid mode 00**
from:
 - in vendor/symfony/mime/FileinfoMimeTypeGuesser.php (line 61)
 - in vendor/symfony/mime/MimeTypes.php -> guessMimeType (line 134)
 - in vendor/symfony/http-foundation/File/File.php -> guessMimeType (line 73)
 - in vendor/symfony/http-foundation/BinaryFileResponse.php -> getMimeType (line 185)
 - in vendor/ankitpokhrel/tus-php/src/Response.php -> prepare (line 131)
 - [...]

Simple and naive solution is using `filetype` from meta data if exists.

links:
* https://forums.aws.amazon.com/message.jspa?messageID=505342

**Comment by ankitpokhrel** [comment]
Hi @pgrzesiecki, the way tus-php interacts with S3 is completely based on PHP stream wrapper and there is no direct integration with any cloud providers. This makes it a bit hard to fully support all the features provided by these cloud providers.

> Simple and naive solution is using filetype from meta data if exists.

I would be glad to review the PR if anyone can work on it. However, this might not work for other cloud providers and should be implemented separately from the default Response handler.
