### ISSUE TITLE
Symfony integration - documentation

### ISSUE THREAD

**Issue by mantis** [ankitpokhrel/tus-php#226]
Hello,

The wiki page for symfony integration shows in the example:

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

this has been deprecated in favour of AbstractController ( https://github.com/symfony/symfony/pull/28243 ) back in August 2018. 

It would be nice to update the example to use Abstract Controller instead:

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
class TusController extends AbstractController
...

**Comment by ankitpokhrel** [comment]
This is updated, thanks!
