### ISSUE TITLE
use S3 upload 10GB+ file very slow 

### ISSUE THREAD

**Issue by kaiwenli** [ankitpokhrel/tus-php#227]
> **Note:** Please report any security issues directly to hello [at] ankit.pl
 
**Describe the bug**

use S3 storage upload 10GB+ file very slow.

**To Reproduce**
1. set s3 config
2. set uppy' config chunkSize: 5242880, resume: true,
3. upload file getting slow.  first request 5s, second  request 10s, third request 15s.

**Expected behavior**

**Screenshots**

**Additional context**
I think S3 upload function have question.  I wrote a file in PHP. 

```php
require 'vendor/autoload.php';
use Aws\S3\S3Client;
use GuzzleHttp\Psr7;

$Bucket = 'tus';
$Key = 'helloworld';

// connect to S3
$s3 = new Aws\S3\S3Client([
    'version' => 'latest',
    'region' => 'us-east-1',
    'endpoint' => 'http://192.168.30.189:9000',
    'use_path_style_endpoint' => true,
    'credentials' => [
        'key' => 'KWCNETADMIN',
        'secret' => 'KWCNETPASSWORD',
    ],

]);

// Get multipart UploadId
$uploadId = $s3->createMultipartUpload(
    [
        'Bucket' => $Bucket,
        'Key' => $Key,
        'state' => [
            'UploadId' => $_GET['id'],
        ],
    ]
);
$uploadId = $uploadId['UploadId'];

// Set upload file path
$uploadFile = '/data/testabc';

$parts = [];

// part filesize
$partSize = 10 * 1024 * 1024;

//part number
$partNumber = 0;

$original = Psr7\stream_for(fopen($uploadFile, 'r+'));

// file part info
$prices = generateMultiuploadParts($original->getSize(), $partSize);

//read file part stream
foreach ($prices as $i => $price) {

    $source = Psr7\try_fopen($uploadFile, 'r');
    $stream = Psr7\stream_for($source);

    $body = new Psr7\LimitStream($stream, $partSize, $price['to']);

    $result = $s3->uploadPart([
        'Bucket' => $Bucket,
        'Key' => $Key,
        'UploadId' => $uploadId,
        'PartNumber' => $i,
        'Body' => $body,
    ]);

    $parts[] = array(
        'PartNumber' => $partNumber++,
        'ETag' => $result['ETag'],
    );

    echo $i . "ok \n";
}
// 4. Complete multipart upload.
$result = $s3->completeMultipartUpload([
    'Bucket' => $Bucket,
    'Key' => $Key,
    'UploadId' => $uploadId,
    'MultipartUpload' => [
        'Parts' => $parts,
    ],
]);

echo "success!";

function generateMultiuploadParts($file_size, $partSize = 5242880)
{
    $i = 0;
    $size_count = $file_size;
    $values = [];
    $partSize = computePartSize($partSize);
    while ($size_count > 0) {
        $size_count -= $partSize;
        $values[] = array(
            'to' => ($partSize * $i),
            'length' => (($size_count > 0) ? $partSize : ($size_count + $partSize)),
        );
        $i++;
    }
    return $values;
}

function computePartSize($partSize)
{
    $partSize = (integer) $partSize;

    return $partSize;
}
```

**Comment by ankitpokhrel** [comment]
Hi @kaiwenli, I don't see any usage of `tus-php` package in the code sample you provided above. You seem to be using [aws-sdk-php](https://github.com/aws/aws-sdk-php) directly for multi-part upload so you should consider [creating an issue in their repo](https://github.com/aws/aws-sdk-php/issues/new/choose) to get help.

**Comment by kaiwenli** [comment]
yeah, i wrote a new PHP code  include aws-sdk-php.

Large file used tus-php's S3  is slow.  tus-php upload file use local storage is normal. 

I think aws-sdk-php's multi-part upload  is good for tus-php.

But I didn't think of a better way to help tus-php's S3 get better upload results when uploading large files.

**Comment by kaiwenli** [comment]
`<?php

use TusPhp\Config;
use TusPhp\Tus\Server;
use TusPhp\File;
use Aws\S3\S3Client;
use Aws\Credentials\Credentials;
use app\index\listener\Tus as Listener;

class Tus
{
    protected $storageConfig = [];
    public function __construct()
    {
        Config::set(env('CONFIG_PATH').'upload.php');
    }
    public function server()
    {
        $this->storageConfig = config('upload.storage');
        if ($this->storageConfig['type'] == 's3') {
            return $this->s3();
        }
        return $this->local();
    }

    public function local()
    {
        $listener = new Listener();
        $server   = new Server('redis');
        $server->setUploadDir($this->storageConfig['local']['uploadDir']);
        $uploadSize = $this->storageConfig['uploadSize'];
        if ($uploadSize) {
            $server->setMaxUploadSize($uploadSize);
        }
        $server->event()->addListener('tus-server.upload.complete', [$listener, 'postUploadOperation']);
        $response = $server->serve();
        $response->send();
        exit(0);
    }
    public function s3()
    {
        $awsAccessKey = $this->storageConfig['s3']['awsAccessKey'];
        $awsSecretKey = $this->storageConfig['s3']['awsSecretKey'];
        $awsRegion    =  $this->storageConfig['s3']['bucket'];
        $basePath     = 's3://'.$this->storageConfig['s3']['bucket'];;
        $endPoint = $this->storageConfig['s3']['endpoint'];
        $listener = new Listener();
        $s3Client = new S3Client([
            'region' => '',
            'version' => 'latest',
            'endpoint' => $endPoint,
            'credentials' => new Credentials($awsAccessKey, $awsSecretKey),
            'use_path_style_endpoint' => true
        ]);
        $s3Client->registerStreamWrapper();

        $server = new Server('redis');
        $server->setUploadDir($basePath);
        $uploadSize = $this->storageConfig['uploadSize'];
        if ($uploadSize) {
            $server->setMaxUploadSize($uploadSize);
        }
        $server->event()->addListener('tus-server.upload.complete', [$listener, 'postUploadOperation']);
        $response = $server->serve();
        $response->send();
        exit(0);
    }
}`

**Comment by kaiwenli** [comment]
I found https://github.com/rafaeltovar/php-tus-aws-s3 on github.

I think this project is good for tus-php. Is it possible to integrate into tus-php.

**Comment by ankitpokhrel** [comment]
> Large file used tus-php's S3 is slow. tus-php upload file use local storage is normal.

`tus-php` support for S3 is via [PHP stream wrapper](https://www.php.net/manual/en/class.streamwrapper.php) interface so a bit discrepancy is expected compared to direct integration using aws SDK. Sadly, there is no plan and resource at the moment to write a wrapper for aws multipart upload but the alternatives like the one you mentioned above can be used.

**Comment by kaiwenli** [comment]
> `tus-php` support for S3 is via [PHP stream wrapper](https://www.php.net/manual/en/class.streamwrapper.php) interface so a bit discrepancy is expected compared to direct integration using aws SDK. Sadly, there is no plan and resource at the moment to write a wrapper for aws multipart upload but the alternatives like the one you mentioned above can be used.


I will try it.  
ok，Thank you very much.
