### ISSUE TITLE
tus-server.upload.complete event (Symfony)

### ISSUE THREAD

**Issue by giloo973** [ankitpokhrel/tus-php#228]
Hello,
 
**Fire event Symfony**
I can't fire events using symfony especially : tus-server.upload.complete, the one that i need.

**To Reproduce**
1. **Uppy:**
```js
<script>
    const uppy = Uppy.Core(
        {
            debug: true,
            autoProceed: false,
            restrictions: {
                maxNumberOfFiles: 1,
                minNumberOfFiles: 1,
                allowedFileTypes: ['video/*', '.mkv']
            },
            allowMultipleUploads: false
        })
        .use(Uppy.Dashboard, {target: '#uppyUploader', inline: true})
        .use(Uppy.Tus, {
            endpoint: "http://localhost/tus/12",
            chunkSize: 20000,
            resume: true,
            limit:1
        });
    uppy.on('upload-success', (file, response) => {
        uppy.setFileState(file.id, { uploadURL: `/redirect/12` });
    })
</script>
```

2. **Server side:**
**Controller**
```php
public function server(TusServerService $tusServerService, Entity $entity): Response{
    $server = $tusServerService->getServer($entity);
    return $server->serve()->send();
}
```
**Service**
```php
public function getServerClip(Clip $clip): TusServer{
    $server = new TusServer();
    $server
        ->setApiPath('/tus/'.$clip->getId()) // tus server endpoint.
        ->setUploadDir($this->params->get('kernel.root_dir') . '/../web/uploads/clip/') // uploads dir.
        ->event()->addListener('tus-server.upload.complete', function (TusEvent $event) {
            // ...
        });
    return $server;
}
```

The event is not called after the upload.... 

What's going wrong ?

**Comment by ankitpokhrel** [comment]
@giloo973 You are calling a method called `getServer` in the controller but in service, I see the listener is attached in `getServerClip` method. Is it a mistake while pasting the code here or are you attaching listener to one server object and using another?

**Comment by giloo973** [comment]
Sorry my mistake ! But in my controller it’s getServerClip which is called.
The upload of the file is good, I get the uploaded file in the right folder. But the event is never called

**Comment by ankitpokhrel** [comment]
@giloo973 The code to attach event looks fine to me. I assume that the event is being fired but is being killed because of some error. Did you check the error logs? It is hard to say anything without additional info.

**Comment by giloo973** [comment]
I know.. the log file is empty... I will investigate again I’ll let you know
