### ISSUE TITLE
How can I do post upload server side processing?

### ISSUE THREAD

**Issue by myscienceisbetter** [ankitpokhrel/tus-php#229]
I'm using tus-php to run the server and I'm interested in doing some server side post processing. 

My users are uploading images and I'd like to do some work on them.

Is this possible?

**Comment by ankitpokhrel** [comment]
Hi @myscienceisbetter, `tus-php` emit events at different stages of upload. If you want to do post-processing, you can listen to `tus-server.upload.complete` event which is emitted after the upload is complete.

More info can be found here: https://github.com/ankitpokhrel/tus-php#events
