### ISSUE TITLE
The Server Headers are duplicated

### ISSUE THREAD

**Issue by Kreateyou** [ankitpokhrel/tus-php#230]
**Describe the bug**
I have successfully run the server and uploads however i have noted that all haeders are duplicated and also error thrown appear twice when implemented in the onComplete Event, this is preventing uppy from uploading as the location detail is concatenated as url1,url2 

**To Reproduce**
Follow all steps

**Comment by ankitpokhrel** [comment]
@Kreateyou are you working on `Windows`? If yes, then this might be related: https://github.com/ankitpokhrel/tus-php/issues/186 

If no, then, can you provide us some info on what environment you are using (OS, framework, cache type, etc) and how you are setting up tus server and middlewares.

**Comment by kohenkatz** [comment]
Posted my solution to this in #186.
