### ISSUE TITLE
Same filenames, safe filenames

### ISSUE THREAD

**Issue by honzahana** [ankitpokhrel/tus-php#233]
Is there any way to store uploaded files with same names? For example store files with incremented filename like: `samename.jpg` and `samename-1.jpg`

It would also be great to have a function that creates safe names. Many European languages contain special characters.

Example: `Příliš žluťoučký kůň úpěl ďábelské ódy.jpg` rename to `prilis-zlutoucky-kun-upel-dabelske-ody.jpg`

[Laravel has similar functionality for strings](https://laravel.com/docs/5.8/helpers#method-str-slug).

**Comment by ankitpokhrel** [comment]
@honzahana `filename` comes from the `Upload-Metadata` sent by the clients. 

If you are using `tus-php` client you can use [file](https://github.com/ankitpokhrel/tus-php/blob/master/src/Tus/Client.php#L83) method to set filename during the request like it is done [here](https://github.com/ankitpokhrel/tus-php/blob/master/example/basic/upload.php#L21).

If you are using, for example [uppy](https://uppy.io/), I guess this can be done by setting the [metaFields](https://uppy.io/docs/tus/#metaFields-null).

**Comment by benjamindoe** [comment]
How do you deal with this if you need to increment on the server to ensure filename uniqueness? As far as I can tell, you can easily change the filename using `$server->event()->addListener('tus-server.upload.complete', function ... ` but you can't get the information back to the client.

For example, I am creating a filename by doing something similar to `bin2hex(random_bytes(16)).'_'.$fileMeta['name']` however you can't get this back to the client. 

I'm currently using uppy to try and do this. You can pass a header so I tried something like `X-Tus-Filename` and it does work but you can't access that from Uppy.

It might be a limitation of Tus but let me know if I'm wrong

**Comment by ankitpokhrel** [comment]
@benjamindoe Yes, you can use events to change the file name in server. But you cannot get the filename back to your client. However you will get the upload location in the header which you can use in your client. 

I am not sure about your usecase but if you need the filename in client then you have to make a separate request in your server to fetch it (you may have to implement some custom endpoint for this).
