### ISSUE TITLE
SF5 support on 1.2.0

### ISSUE THREAD

**Issue by darthf1** [ankitpokhrel/tus-php#234]
I noticed in the changelog that `1.2.0` supports `SF5.0`. I get the following during install:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ankitpokhrel/tus-php 1.2.0 -> satisfiable by ankitpokhrel/tus-php[v1.2.0].
    - ankitpokhrel/tus-php v1.2.0 requires symfony/console ^3.4 || ^4.0 -> no matching package found.
```

In [composer.json](https://github.com/ankitpokhrel/tus-php/blob/v1.2.0/composer.json) only SF 3.4 and SF 4 are listed.
```
    "symfony/console": "^3.4 || ^4.0",
    "symfony/event-dispatcher": "^3.4 || ^4.0",
    "symfony/http-foundation": "^3.4 || ^4.2"
```

**Comment by ankitpokhrel** [comment]
@darthf1 you need to use `symfony-5` as mentioned in the [doc](https://github.com/ankitpokhrel/tus-php#installation).

```bash
composer require ankitpokhrel/tus-php:dev-symfony-5
```

**Comment by darthf1** [comment]
Ok. I just got confused by the change log then. I'm back on the separate branch.

**Comment by ankitpokhrel** [comment]
You can now try out v2.0 before it gets released.

```
composer require ankitpokhrel/tus-php:v2.x-dev
```

See #264
