### ISSUE TITLE
Click the pause button and then upload offset = 0

### ISSUE THREAD

**Issue by peiweijianphp** [ankitpokhrel/tus-php#240]
> **Note:** Please report any security issues directly to hello [at] ankit.pl
 
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by peiweijianphp** [comment]
$file = $this->buildFile([
            'name' => $fileName,
            'offset' => 0,
            'size' => $this->getRequest()->header('Upload-Length'),
            'file_path' => $filePath,
            'location' => $location,
        ])->setKey($uploadKey)->setChecksum($checksum);

**Comment by peiweijianphp** [comment]
server class handlePost function

**Comment by peiweijianphp** [comment]
1

**Comment by ankitpokhrel** [comment]
Hi @peiweijianphp 

If you are getting upload offset as 0, it is highly likely that the cache is not configured properly. Make sure that the entries are being saved properly in your cache.

**Comment by peiweijianphp** [comment]
My operating environment is docker + php7.2 + redis5 and The client uses uppy.js
My problem is: When the upload progress bar is less than 100%, the offerkey of tus PHP response is' ', so every time you click pause, it will start from 0. When the upload progress is 100%, the offerkey in redis will change, the file will be merged, and the progress bar of uppy.js is 100%. When the uploaded file is large, the client will have to wait
![bug](https://user-images.githubusercontent.com/20853718/75941983-237dae80-5ecc-11ea-8102-a41195dfde57.png)

**Comment by markkimsal** [comment]
@peiweijianphp 
In Uppy, set the "chunkSize: 5000000" for the `Uppy.Tus` plugin.

```js
    const uppy = Uppy.Core({debug: true, autoProceed: false})
    .use(Uppy.Dashboard, {target: '#uppyUploader', inline: true, resumableUploads: true})
    .use(Uppy.Tus, {
        endpoint: 'http://your-server/endpoint/',
        chunkSize: 5000000,  // this line
        resume:true,  // and maybe this one
    }) 
    .run() 
```
This took me quite a while to track down.  I find it strange that a project that bills itself as "resumable uploads" doesn't have the examples setup to resume uploads.

To be fair, the "basic" example was able to resume uploads, but only after I uploaded the entire file to the server.  Then the client would resume sending to the server (which was on the same machine ...)

**Comment by markkimsal** [comment]
@peiweijianphp 
upon further digging, nginx requires `fastcgi_request_buffering off;`

```
    location ~ \.php$ {
        fastcgi_request_buffering off;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
    }
```

@ankitpokhrel
This `fastcgi_request_buffering off'` should be in the docs section around nginx.  Otherwise, nginx will buffer the entire POST / PATCH body to memory or disk before initiating the fastcgi request to PHP.  That's why forcing the JS client to send in chunks worked, because it was sending dozens of small complete requests.

**Comment by ankitpokhrel** [comment]
@markkimsal Thank you so much for debugging this 👏 👏 👏
