### ISSUE TITLE
Uppy and metadata

### ISSUE THREAD

**Issue by duerrsimon** [ankitpokhrel/tus-php#242]
I wanted to use uppy metadata to do some server side processing (setting the page id in my CMS). 
```
<script src="https://transloadit.edgly.net/releases/uppy/v1.4.0/uppy.min.js"></script>
  <script>
    const uppy = Uppy.Core({
debug: true,
 autoProceed: false, 
meta: {
  offset: 1488
}
 })
      .use(Uppy.Dashboard, {target: '#uppy-box', inline: true})
      .use(Uppy.Tus, {endpoint: 'https://localhost/uppy/', limit:10});
  </script>
```

I also tried using another meta like pageid:1488 instead of the offset and I tried both getFile() and getRequest() but I cannot get the metadata information. What do I need to do?

Server-side code:
```
$server->event()->addListener('tus-server.upload.complete', function(\TusPhp\Events\TusEvent $event) {
	$fileMeta = $event->getFile()->details();
	//$pageid=$event->getRequest()->extractMeta('pageid');
       $pageid=$fileMeta['offset']
	$file_path = $event->getFile()->getFilePath();

// further processing here with $pageid. But $pageid is empty
});
```

The configuration works as the files are uploaded to the specified tempory directory. The only problem is retrieving the meta data.

**Comment by Amerlander** [comment]
Is your event listener fired at all? It has to be before `$server->serve()`.

This:
```php
$server   = new \TusPhp\Tus\Server();

$server
    ->setApiPath('x')
    ->setUploadDir('y')
    ->event()->addListener('tus-server.upload.complete', function (\TusPhp\Events\TusEvent $event) {
        $fileMeta = $event->getFile()->details();
        bDump($fileMeta);
        // ...
    });

$response = $server->serve();

$response->send();
```
returns that:
![image](https://user-images.githubusercontent.com/3764089/75083553-b3f5df80-5519-11ea-8d59-5e35aa9ba68c.png)

**Comment by Amerlander** [comment]
Oh, I just saw youre trying to get the uppy meta directly, but it is scoped in `metadata`.
So maybe changing `$pageid=$fileMeta['offset']` to `$pageid=$fileMeta['metadata']['offset']` already helps?

**Comment by Amerlander** [comment]
sorry, it was too late for me. The user metadata is not there.

My above screenshot should also contain some user meta since in Uppy I have  this:
```js
meta: {
    user: 'John',
},
```
It seemed to work someday, I wonder if https://github.com/ankitpokhrel/tus-php/pull/166 is broken now or if its caused by changes in Uppy.

So were both having the same issue now :)

**Comment by Amerlander** [comment]
seems to be an issue in Uppy, when I downgrade Uppy to 1.8.0 everything works.
Uppy 1.9.1 and 1.9.2 are both broken.

**Comment by duerrsimon** [comment]
I got it working now to. I tested with uppy 1.8.0 and uppy 1.9.2 and there are no issues. Seems like there is no bug in uppy. I am closing this now. Thanks for helping out! I set the meta directly when initalizing uppy.
For reference, I used the following code:

```
$td = $files->tempDir('uppy'); // CMS
$td_path = (string) $td;

// Create TusPhp server
$server = new \TusPhp\Tus\Server();
// Set path to endpoint - no trailing slash here
$server->setApiPath('/uppy');
// Set upload directory
$server->setUploadDir($td_path);

// Listener function for when an upload is completed
$server->event()->addListener('tus-server.upload.complete', function(\TusPhp\Events\TusEvent $event) {
	$file_path = $event->getFile()->getFilePath();
	p = wire('pages')->get(intval($event->getFile()->details()['metadata']['pageid']));
	$p->of(false); // CMS related
       $p->files->add($file_path); //CMS related
	$p->save('files'); //CMS related
});
// Send response
$response = $server->serve(); 
$response->send();
exit(0);
```

```
<script src="https://transloadit.edgly.net/releases/uppy/v1.9.2/uppy.min.js"></script>
  <script>
    const uppy = Uppy.Core({debug: true, autoProceed: false, meta: {
  pageid: 1488
} })
      .use(Uppy.Dashboard, {target: '#uppy-box', inline: true})
      .use(Uppy.Tus, {endpoint: 'MYURL/uppy/', limit:10});
  </script>
```
