### ISSUE TITLE
Upload to 37% click pause, but still upload from 0%

### ISSUE THREAD

**Issue by peiweijianphp** [ankitpokhrel/tus-php#243]
![bug1](https://user-images.githubusercontent.com/20853718/75126786-7dc18700-56f6-11ea-991d-9a0f9b5f8cd6.png)
![bug2](https://user-images.githubusercontent.com/20853718/75126832-b6f9f700-56f6-11ea-9ca5-30d77fe72d35.png)

**Comment by peiweijianphp** [comment]
The client uses uppy.js ,  Only when it is 100%, the backend will respond to the request of the patch, and the file will be uploaded

**Comment by ankitpokhrel** [comment]
Closing as a duplicate of #44
