### ISSUE TITLE
No longer compatible with frameworks that use newer Symfony packages.

### ISSUE THREAD

**Issue by stephan-v** [ankitpokhrel/tus-php#245]
Hello,

This package is unfortunately no longer compatible with packages that use newer Symfony packages like `symfony/console` which is already  up to `v5.0.5`.

Could the requirements of the `package.json` be updated? I don't think it will lead to breaking changes.

For example I can no longer use this when using something like Laravel 7.0

**Comment by ankitpokhrel** [comment]
Hi @stephan-v 

Please use `symfony-5` branch for Symfony 5 packages support

```bash
$ composer require ankitpokhrel/tus-php:dev-symfony-5
```

**Comment by stephan-v** [comment]
Thanks a lot.

**Comment by lalithhakari** [comment]
Thank you... i was facing the issue..you helped me...

**Comment by skyronic** [comment]
@ankitpokhrel any ETA on a "stable" release with symfony-5 support?

**Comment by ankitpokhrel** [comment]
@skyronic did you faced any problem when using `symfony-5` branch? The build is quite stable and is usually up to date.

**Comment by ankitpokhrel** [comment]
You can now try out v2.0 before it gets released.

```
composer require ankitpokhrel/tus-php:v2.x-dev
```

See #264
