### ISSUE TITLE
Are there speed limitations in the server setup?

### ISSUE THREAD

**Issue by kaarta-dstrickler** [ankitpokhrel/tus-php#246]
**Is your feature request related to a problem? Please describe.**
I'm not sure where to ask this, so I put it here. 

We're using Uppy's Dashboard on the client and your code on the server side. We’re seeing about 38Mb/s when uploading to an AWS server, but  we can use Linux’s “scp” command to push about 115Mb/s to it. We’ve also tested SFTP (I know this is just like scp) with the same results. My gut is Uppy can handle much more than a 38Mb/s upload speed, and we've implemented the server side wrong.

Since I know the problem isn’t the internet line, my guess is a the Tus protocol must have _some_ overhead to it, but again, this looks like _much_ more overhead than I would expect (I'd expect ~10%).

Are there any limitations to the server side in your code for speeds under 1GB? Anything you think I should check in our code?

TIA,

Dave

**Comment by ankitpokhrel** [comment]
Hi @kaarta-dstrickler 

There is no speed limitation as such. But be aware that `tus-php` support for S3 (an other cloud services) is via [PHP stream wrapper](https://www.php.net/manual/en/class.streamwrapper.php) interface so a bit discrepancy is expected compared to the direct integration using AWS SDK. 

Sadly, there is no plan and resource at the moment to write a wrapper for [S3 multipart upload](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html) which might enhance S3 upload experience. But we are open to any contributions :)

Related #227

**Comment by markkimsal** [comment]
I've had good luck with `$bytes = stream_copy_to_stream($input, $output, self::CHUNK_SIZE);` and increasing the CHUNK_SIZE;

`fread()` is limited to 8192 bytes, meaning that PHP will have to talk to redis (or write json blobs to the FS) many times to upload a large file.  `stream_copy_to_stream` does not have that limitation and will report back how many bytes were written.  This only helps when also increasing the CHUNK_SIZE to reduce the amount of thrashing around that happens at the PHP level.

**Comment by kaarta-dstrickler** [comment]
> I've had good luck with `$bytes = stream_copy_to_stream($input, $output, self::CHUNK_SIZE);` and increasing the CHUNK_SIZE;
> 
> `fread()` is limited to 8192 bytes, meaning that PHP will have to talk to redis (or write json blobs to the FS) many times to upload a large file. `stream_copy_to_stream` does not have that limitation and will report back how many bytes were written. This only helps when also increasing the CHUNK_SIZE to reduce the amount of thrashing around that happens at the PHP level.

Could you let me know what file and line(s) of code I'm looking for? I'd like to try this out, but don't know where the fread() is

**Comment by samundra** [comment]
@kaarta-dstrickler Likely https://github.com/ankitpokhrel/tus-php/blob/master/src/File.php#L424-L433

**Comment by kaarta-dstrickler** [comment]
> @kaarta-dstrickler Likely https://github.com/ankitpokhrel/tus-php/blob/master/src/File.php#L424-L433

Thanks for the code reference! Doing a little debugging I stumbled across something strange. I was trying to make sure I was adjusting the right code, so quickly inserted an exit() to force the upload to bomb. To my surprise, not only did the upload work, but the speed improved by over 5x, even though the CHUNK_SIZE is still the default of 8192.

Not knowing the inner workings of Uppy code, I poked around and found that the client.php uses "function getData(int $offset, int $bytes)" uses this read() function, but it still leaves me puzzled.

What am I not understanding?

```
public function read($handle, int $chunkSize) : string
{
        $data = fread($handle, $chunkSize);

        /*
         * DStrickler 12:03 PM 10/29/20
         * Why does putting an exit() here not crash the upload?
         * It seems to work well *without* this code working.
         * Previous speed was maxed at about 75Mb/s, but now
         * with this exit() is about 500Mb/s on a 1Gb/s connection.
         */
        exit() ;
}
```

**Comment by kaarta-dstrickler** [comment]
I think I found the solution, and remember I am uploading files that routinely are over  1GB, and increasing over 10GB.

1) Altered the constant at the top of the ../src/File.php to have
```public const CHUNK_SIZE = 8192 * 128; // 8 kilobytes * 128 *  = 1M packets.```

2) The in the function read(), I swaped out the fread() line to use
```$data = stream_get_contents($handle,  self::CHUNK_SIZE);```

I've now gone from about 75Mb/s upload to about 450Mb/s on a FiOS line that clocks out at about 830Mb/s - a _huge_ improvement. While I recognize my packet size is really large, I think it's appropriate for the size of these files, and more importantly the fast speed of the FiOS line.

Many thanks to all who chimed in on this!

-- Dave

**Comment by samundra** [comment]
Hi @kaarta-dstrickler 

Thank you for taking time to write back on comment regarding the changes.

Going from 75Mb/s upload to ~450Mb/s  is indeed a huge improvement. If I am not wrong you were able to get almost 50% of the total speed on FiOS line 830Mb/s.

Could you please share insights on how you performed the benchmark? If possible, could you also please mention the tools and methodologies. This is very interesting topic and only on rare occassions we go this far to benchmark it. This is one of them. Thus, we would like to catch-up on this opportunity and would like to gain as much information as possible. This would help us in further development of the library. 

I will reopen this issue as we'll keep watch on it for a while.

**Comment by kaarta-dstrickler** [comment]
@samundra I'd be happy to help if I can. I love Uppy!

I am testing on a home-based FiOS line that I test for speed automatically once an hour with iperf3 from a Raspberry4 with a 1Gb network connection. It verifies the line at about 850Mb/s to 950Mb/s, which is about as good as I can expect due to overhead, etc. When these tests are done, all connections are hard-cabled with Cat7 wires, making sure that WiFi never gets in the mix to slow things down on my home network. I use Unifi equipment at home (WiFi, Hub, Gateway).

When using Uppy, I am testing from a 2yr old MacBook Pro, which when using iPerf3, tests out at the same 850Mb/s to 950Mb/s speeds. When using Uppy on this Macbook Pro, I am connecting to an AWS server running an instance that can handle > 1Gb/s speeds (according to AWS). As my FiOS line won't go faster than 1Gb/s, I can't verify this. The backend that the Uppy client is talking to is the stock Uppy PHP implementation, except for the small changes I've noted previously in buffering.

While I am thrilled to see such a speed improvement, it's curious to notice it's about 50% of the actual FiOS speed. I also tried this over WiFi, which iPerf3 reports at a fairly steady 300Mb/s, but Uppy still shows about 50% of the WiFi, so clocking about a 150Mb/s speed. I mention this because it appears that the 50% is "overhead", but I don't see much traffic on the download side which I am performing and upload via Uppy - certainly not anywhere close to clog the FiOS line. Perhaps the overhead is on the server side. I have tried this with have the Uppy server write temp files to the AWS disk as well as use Redis to avoid the disk latency.

What I have not tried is the Uppy client running against any other Uppy server backend, so perhaps the "50%" issue is the way I am running the backend.

I hope all of this helps. Please let me know if you need any more information.

**Comment by markkimsal** [comment]
@kaarta-dstrickler 
I think what's happening is that the client is sending all the data up to the PHP.  Then the PHP quits.  Then the client continues to send the next chunk of data to another apahce/nginx/php-fpm thread.  Thus, you are only testing upload speed w/o the slowness of PHP having to actually read the data and do anything with it.

I'm curious, does the resulting uploaded file actual have the same md5 sum or data length as what's being uploaded?  Or is this just an appearance of speed increase because half the system is removed from the equation?

**Comment by kaarta-dstrickler** [comment]
> Update:
> Sorry, I was reading comments in my inbox out of order. There was some comment about increasing speed by putting in an `exit()` call. I don't see this comment on this thread so it was probably deleted. The following comment can be ignored.

Yes, that was me deleting it. I posted it, then realized the exit() was doing just what you said it was (throwing away data) and thus giving me false speed readings. I deleted the post, and continued to test without the exit(), and got speed results pretty close to what you'll see above. Thus, I'm pretty sure the writing to disk/redis by the PHP server-side was only adding a small amount of overhead.

**Comment by sQty** [comment]
have this problem too....

all visible here ...

![139915611-eed53174-87dd-4b61-a056-d792fd712ff4](https://user-images.githubusercontent.com/13269086/140015569-2f4860a8-7917-49a9-b65a-839160be28e0.jpg)

upload to uppy demo server tus  ( this implementation dunno ) 

so i downloaded uppy js client and this php server 
and have similar speeds on lan  upload ....
