### ISSUE TITLE
How to use this library with CodeIgniter 3

### ISSUE THREAD

**Issue by hatimdisawala** [ankitpokhrel/tus-php#248]
Hi,

Add documentation for using this library with CodeIgniter 3.

**Comment by ankitpokhrel** [comment]
Hi @hatimdisawala 

I am not quite familiar with CodeIgniter so cannot advise you much on that. Take a look at this comment, it might help you to get started: https://github.com/ankitpokhrel/tus-php/issues/54#issuecomment-397226904.
