### ISSUE TITLE
symphony/console v5 support

### ISSUE THREAD

**Issue by paul-a-byford** [ankitpokhrel/tus-php#250]
**Is your feature request related to a problem? Please describe.**
Can tus-php support symfony/console v5?

I've recently attempted to upgrade to recent major release of laravel (laravel v7). laravel v7 has upgraded to symfony 5, but unfortuantely this cause a clash with tus-php supporting upto v4.4 of symfony/console

**Describe the solution you'd like**
Tus-php to support symfony/console v5

**Describe alternatives you've considered**
None

**Additional context**
The specific issue i'm having is where tus-php is used within the vimeo package - see specific screenshot of the problem at this linked issue https://github.com/vimeo/laravel/issues/72

**Comment by ankitpokhrel** [comment]
@paul-a-byford please use symfony-5 branch for Symfony 5 support.

```bash
$ composer require ankitpokhrel/tus-php:dev-symfony-5
```

**Comment by ankitpokhrel** [comment]
You can now try out v2.0 before it gets released.

```
composer require ankitpokhrel/tus-php:v2.x-dev
```

See #264
