### ISSUE TITLE
Update dependencies to use Symfony 5 components

### ISSUE THREAD

**Issue by bledson** [ankitpokhrel/tus-php#253]
I tried to update my laravel 5.6 project to laravel 7.0, but my vimeo/laravel dependency, but it turns out that since this package depends on symfony 3-4, makes vimeo/laravel package incompatible with the newer laravel version.

**Comment by ankitpokhrel** [comment]
@bledson  you can do this:

1. Install `ankitpokhrel/tus-php:dev-symfony-5` branch and alias it as `1.0`.
   ```
   $ composer require "ankitpokhrel/tus-php:dev-symfony-5 as 1.0"
   ```

2. Install `vimeo/laravel` as usual.
   ```
   $ composer require vimeo/laravel
    ```

**Comment by larowlan** [comment]
Are there plans for a 2.x release from the symfony 5 branch? Thanks

**Comment by amodliszewski** [comment]
Bump, would love to know more about release  of sf5 support branch

**Comment by ankitpokhrel** [comment]
@larowlan @amodliszewski I will try to release v2.0 soon, possibly within few weeks.

**Comment by larowlan** [comment]
thanks @ankitpokhrel fwiw I have a test-suite for a project that uses this so let me know if you need more testing

**Comment by ankitpokhrel** [comment]
You can now try out v2.0 before it gets released.

```
composer require ankitpokhrel/tus-php:v2.x-dev
```

See #264
