### ISSUE TITLE
How can I plugin the library with my remote CakePHP Redis

### ISSUE THREAD

**Issue by ouissla** [ankitpokhrel/tus-php#256]
Hi,

I am setup the library on CakePHP following the integration example. My application is using Redis on AWS Elasticache as the default caching mechanism.

How do I tell the library to use the existing Redis server? When I initialize the server:
`$server = new TusServer('redis');` 

I get a connection refused to: `tcp://127.0.0.1:6379` instead of something like xxx.xxx.xx.xxxx.cache.amazonaws.co:6379

Thanks,

**Comment by ankitpokhrel** [comment]
@ouissla Default redis and file configuration for server and client can be found inside `<vendor>/ankitpokhrel/tus-php/config/server.php` and `<vendor>/ankitpokhrel/tus-php/config/client.php` respectively. To override default config you can simply copy these files to your preferred location and update the parameters. You then need to set the config before doing anything else.

```php
\TusPhp\Config::set('<path to your config>');

$server = new \TusPhp\Tus\Server('redis');
```

Alternately, you can set `REDIS_HOST`, `REDIS_PORT` and `REDIS_DB` env in your server to override redis settings for both server and client.

**Comment by ouissla** [comment]
Hey mate, I haven't had time to test this out but just taking the time to thank you for your answer.
