### ISSUE TITLE
Simultaneous file uploads can cause files to be corrupted when using the file cache

### ISSUE THREAD

**Issue by jtenhave** [ankitpokhrel/tus-php#257]
**The Issue:**
When uploading 2 or more files simultaneously, and using the 'file' cache, the uploaded files can become corrupted.

**My Setup:**
- Apache
- tus-php 1.2.0
- Uppy Tus Client
- Chunk Size 10 MB 

**Steps To Reproduce:**
This issue can be fairly hard to reproduce since (I suspect) it is caused by a race condition. I first noticed it when uploading three large files (~750MB) simultaneously.

1.  Setup the tus-php server. The [sample](https://github.com/ankitpokhrel/tus-php#server) code will do. Change cache type to 'file'.

2.  Start uploading 3-4 large (at least 100MB) files at the same time. Note: I am using multiple instances of my upload page, and not just uploading multiple files with the same client on one page.

3. Open the browser developer tools network tab for each of the pages that is uploading a file.

4. Look for upload chunk (PATCH) requests that fail with a '409: Conflict' response. Look at the 'Upload-Offset' header in the response and notice that it is less than 'Upload-Offset' header in the previous successful chunk response, which does not make sense. This is a sign that the file could be corrupted.

5. At this point the client should recover and send the correct data indicated by 'Upload-Offset' in the '409: Conflict' response. Let the file upload run to completion.

6. Once the upload is completed, look at the size of the uploaded file on the server and compare it to the size of the file you uploaded. They are not the same, meaning the uploaded file is corrupted.

**Additional context:**
After doing some digging, I believe there is a race condition when updating the cache file. This results in the wrong offset value being stored for a given file, causing it to be corrupted. I suspect the issue is in [FileStore::set()]( https://github.com/ankitpokhrel/tus-php/blob/8d874b8cf80153eda43ecddf97d9cd6a0a11ad1b/src/Cache/FileStore.php#L174).  This function will read the cache file, make changes, and then write the whole cache file again. Process A reads the cache file. Process B writes changes to the cache file. Finally Process A writes changes to the cache file, overwriting the changes made by process B.

**Comment by ankitpokhrel** [comment]
Hi @jtenhave 

I assume you are uploading different files and not the same file in parallel. In case you are trying to upload the same file in parallel then there are some limitations and it needs to be handled in a different way, see #100.

I tried it quickly but was not able to reproduce the issue. However the issue seems valid and we will investigate it when we have some time. Thank you for reporting!

On a side note, file cache was initially designed to make it easy to work and debug dev env and is not recommended to use it in production.
