### ISSUE TITLE
v1.2.1 Release

### ISSUE THREAD

**Issue by jnbn** [ankitpokhrel/tus-php#258]
ramsey/uuid update on composer.json is crucial for updating some dependancies on Laravel framework. Can you please tag 1.2.1 with updated composer?

**Comment by ankitpokhrel** [comment]
Please use `symfony-5` branch form Laravel 7 support until new version is released. See https://github.com/ankitpokhrel/tus-php/issues/253#issuecomment-604649273

**Comment by ankitpokhrel** [comment]
You can now try out v2.0 before it gets released.

```
composer require ankitpokhrel/tus-php:v2.x-dev
```

See #264

**Comment by jnbn** [comment]
Seems it's broken as @ankitpokhrel removed 2.x-dev branch and released 2.0 officially. Anybody having the same problem can follow https://github.com/vimeo/vimeo.php/pull/259 for now or use https://github.com/mstaack/vimeo.php/tree/patch-1 as vimeo-php dependancy.
