### ISSUE TITLE
16MB video within the library source code

### ISSUE THREAD

**Issue by gdarko** [ankitpokhrel/tus-php#259]
We are including the library in WordPress plugin but it is very big. There is video within the library that is literaly 16 MB which is too much for projects limited on size. Can this be moved out of the project somehow?

Thanks.

**Comment by ankitpokhrel** [comment]
@gdarko Please fetch the project using [composer](https://getcomposer.org/) as described in [this doc](https://github.com/ankitpokhrel/tus-php/wiki/WordPress-Integration). All unnecessary files will automatically be excluded.

**Comment by gdarko** [comment]
Thank you @ankitpokhrel , i just noticed it is removed
