### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by emresaracoglu** [ankitpokhrel/tus-php#260]
It fails due to 403 during uploading. I can't find the reason for this. 

What is your idea?

Thanks

> Request URL: https://my.example.com/files/c23a9ae6-4e5e-4810-af4d-3e03a6003d48
> Request Method: HEAD
> Status Code: 200 

> Request URL: https://my.example.com/files/c23a9ae6-4e5e-4810-af4d-3e03a6003d48
> Request Method: PATCH
> Status Code: 403 

Console

> [Uppy] [23:40:58] Failed to upload Name.pdf tus: unexpected response while uploading chunk, originated from request (response code: 403, response text: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>403 Forbidden</title>
> </head><body>
> <h 1>Forbidden</h 1>
> <p>You don't have permission to access /files/c23a9ae6-4e5e-4810-af4d-3e03a6003d48
> on this server.<br />
> </p>
> </body></html>
> )

**.htaccess**

```
<Limit GET POST PUT DELETE HEAD OPTIONS PATCH>
Order allow,deny
Allow from all
</Limit>

<IfModule mod_rewrite.c> 
	SetEnv HTTP_MOD_REWRITE On
		RewriteEngine on  
    	RewriteBase /
    	## If the request is for a valid directory
        RewriteCond %{REQUEST_FILENAME} -d [OR]
        ## If the request is for a valid file
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        ## If the request is for a valid link
        RewriteCond %{REQUEST_FILENAME} -l 
        RewriteRule ^ - [L] 
        RewriteRule ^files/?(.*)?$ /includes/server.php?$1 [QSA,L]
     
        RewriteRule ^([^/]+)/?$ index.php?id=$1 [L,QSA]
 
</IfModule>

```

**server.php**
```

include "vendor.php";
	
	use TusPhp\Tus\Server;
	
	$server = new Server(); 
	$server->setMaxUploadSize(100000000);
	$server->setUploadDir('/home/username/public_html/');
	$response = $server->serve();
	$response->send();
	exit(0); 
```

**upload.php**

```
 <?php
	include "vendor.php";

	use TusPhp\Tus\Client;
	use TusPhp\Exception\FileException;
	
	
	$client = new \TusPhp\Tus\Client('https://my.example.com/files/');

	if (!empty($_FILES)) {
		$status = 'new';
		$fileMeta = $_FILES['tus_file'];
		$uploadKey = hash_file('md5', $fileMeta['tmp_name']);
		try {
			$offset = $client->setKey($uploadKey)->file($fileMeta['tmp_name'])->getOffset();
			if (false !== $offset) {
				$status = $offset >= $fileMeta['size'] ? 'uploaded' : 'resume';
			} else {
				$offset = 0;
			}
			echo json_encode([
				'status' => $status,
				'bytes_uploaded' => $offset,
				'upload_key' => $uploadKey,
			]);
		} catch (ConnectException $e) {
			echo json_encode([
				'status' => 'errorconnect',
				'bytes_uploaded' => -1,
			]);
		} catch (FileException $e) {
			echo json_encode([
				'status' => 'resume',
				'bytes_uploaded' => 0,
				'upload_key' => '',
			]);
		}
	} else {
		echo json_encode([
			'status' => 'error',
			'bytes_uploaded' => -1,
		]);
	}
```

**Comment by ankitpokhrel** [comment]
@emresaracoglu This can be becuase of various reason. Please check your apace configuration and make sure that the user that run apache has a proper permission to read and write folder contents. Also check the error.log, usually located at `/var/log/apache2/error.log`, which will help you to identify why you get the 403 error.
