### ISSUE TITLE
Flysystem support

### ISSUE THREAD

**Issue by benjamindoe** [ankitpokhrel/tus-php#265]
**Is your feature request related to a problem? Please describe.**
Support for [Flysystem](https://github.com/thephpleague/flysystem) would be really handy as this filesystem abstraction is used by _many_ projects.

**Describe the solution you'd like**
A Flysystem adapter could be passed into the `Server` object to initialise the connection. The `Server` would then be able to store data directly to the Flysystem disk. 

**Additional context**
This would create a huge I/O boost as currently the only method to do with Flysystem is have the file moved to the disk once it has been written to a local disk. The issue here is usage in a serverless environment where local disk space is limited and it is preferable to interact directly to Flysystem disks which may be remote or cloud disks. The other issue with storing it locally and moving it to a remote disk is that the `GET` part of tus is broken.

**Comment by darthf1** [comment]
Would be great if this can be supported. Im deploying my symfony app to Kubernetes and would like to abstract my filesystem as well.

**Comment by renepardon** [comment]
Is there an update on the "discussion"?
