### ISSUE TITLE
File type or extension

### ISSUE THREAD

**Issue by erfansahaf** [ankitpokhrel/tus-php#266]
Since the TUS protocol transfers data through the HTTP requests (POST and PATCH), we can't access file extension/type or such with $_FILE.

I want to know is there any way to control and validate the uploaded file type and reject it if it isn't allowed? I tried to get the file extension by its name in a Middleware but it was empty.

Thanks.

**Comment by mbaumgartl** [comment]
This is not really supported by the protocol (see [FAQ](https://tus.io/faq.html#how-can-i-get-the-file-name-or-file-type-for-an-upload)).

As described: adding the file type to the meta data and check it in a middleware, seems to be the only solution at the moment.

**Comment by erfansahaf** [comment]
@mbaumgartl Thanks. But why the file name is empty when I try to access it in the middleware request?

**Comment by mbaumgartl** [comment]
@erfansahaf: It's hard to say without seeing any code :wink:

**Comment by ankitpokhrel** [comment]
@erfansahaf you need to use middleware as @mbaumgartl suggested. Something like this will work.

```php
<?php

class FileTypeValidator implements TusPhp\Middleware\TusMiddleware
{
    public function handle(TusPhp\Request $request, TusPhp\Response $response)
    {
        $filename = $request->extractFileName();

        // Extract file type and check if it is valid.
    }
}

$server = new TusPhp\Tus\Server('redis');

$server->middleware()->add(FileTypeValidator::class);

// ...
```

**Comment by erfansahaf** [comment]
When I try to access the filename in the middleware, it a zero-length string. @mbaumgartl @ankitpokhrel 

server.php:
```php

    $server   = new \App\Classes\TusServer('redis');

    $server->setApiPath('/files');
    $server->middleware()->add(\App\Middleware\Authenticator::class);
    $server->middleware()->add(\App\Middleware\CheckFileType::class);

    $server->event()->addListener('tus-server.upload.complete', function (\TusPhp\Events\TusEvent $event) {
        $filename = $event->getFile()->getName(); // the filename is accessible when in uploading is finished, but not in the middleware
        }
    });

    $tus = $server->serve();
    $tus->send();
    exit(0);

```

CheckFileType.php:
```php
<?php
namespace App\Middleware;

use App\Classes\Auth;
use App\Exceptions\TokenMismatchException;
use TusPhp\Middleware\TusMiddleware;
use TusPhp\Request;
use TusPhp\Response;

class CheckFileType implements TusMiddleware
{
    /**
     * {@inheritDoc}
     */
    public function handle(Request $request, Response $response)
    {
        $filename = $request->extractFileName(); // It's an empty string ""
    }
}
```

**Comment by ankitpokhrel** [comment]
@erfansahaf It is because `Upload-Metadata` header is only present during creation i.e `POST` request. In your case, it makes sense to validate file type and reject the upload at this point as creation is the first step of execution.

```php
<?php

use Symfony\Component\HttpFoundation\Request as HttpRequest;

class FileTypeValidator implements TusPhp\Middleware\TusMiddleware
{
    public function handle(TusPhp\Request $request, TusPhp\Response $response)
    {
        if ($request->method() === HttpRequest::METHOD_POST) {
            $filename = $request->extractFileName(); // Filename should be available here.

            // Extract file type and error out if it is not valid.
        }
    }
}
```

**Comment by chatlumo** [comment]
Hi,

Thanks about it.

I use that :
`$server->event()->addListener('tus-server.upload.created', function (\TusPhp\Events\TusEvent $event) {
    $metadatas = $event->getFile()->details()['metadata'];

});`

What is the code to reject upload if $metadas value is not what I want ?

**Comment by mbaumgartl** [comment]
@chatlumo: I don't think an event listener is the right place for the validation.

Just write a middleware (as shown above) and have a look at ``extractAllMeta`` or ``extractMeta`` methods of the request object.
