### ISSUE TITLE
Tus server not found

### ISSUE THREAD

**Issue by dusanjablanovic2224** [ankitpokhrel/tus-php#269]
Hello everyone,
I integrated Tus server in Laravel application but when I dump : 
$response = app('tus-server')->serve();
    dd($response);
 the message is :  
Response {#493 ▼
  +headers: ResponseHeaderBag {#494 ▶}
  #content: ""
  #version: "1.0"
  #statusCode: 404
  #statusText: "Not Found"
  #charset: null
}

**Comment by biholaindrasinh** [comment]
I have tried this and it works. [https://github.com/ankitpokhrel/tus-php/issues/245](#245)

**Comment by biholaindrasinh** [comment]
I have tried this and it works. [https://github.com/ankitpokhrel/tus-php/issues/245](#245)

**Comment by ankitpokhrel** [comment]
@dusanjablanovic2224 Its hard to say anything based on the details you shared but I assume that you might have missed some steps when setting up the package. You can find setup instructions for Laravel [here](https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration). The instructions are based on Laravel5 so few things might have got changed in the new version, yet, it should give you the general idea.
