### ISSUE TITLE
Deprecated Notice from Symfony HttpFoundation\Response

### ISSUE THREAD

**Issue by martincarlin87** [ankitpokhrel/tus-php#274]
**Describe the bug**
It looks like the Symfony dependencies have had a version bump and are now throwing a deprecated notice:

```
Since symfony/http-foundation 5.1: The "Symfony\Component\HttpFoundation\Response::create()" method is deprecated, use "new Symfony\Component\HttpFoundation\Response()" instead.
```

**To Reproduce**
1. Run `composer update`
2. Upload file

**Expected behavior**
No deprecation notice.

**Screenshots**

This is the diff in dependencies:

![image](https://user-images.githubusercontent.com/1721925/84755507-9dd4c900-afb9-11ea-9400-a41013133e85.png)

**Additional context**

I believe the issue is in https://github.com/ankitpokhrel/tus-php/blob/master/src/Response.php, but not sure if it is as easy as using `new` instead of `::create` or if the class would need a little refactoring.

Hope it helps

**Comment by ankitpokhrel** [comment]
Thank you for reporting :)
