### ISSUE TITLE
dynamic upload path laravel php tus

### ISSUE THREAD

**Issue by imRezaAlie** [ankitpokhrel/tus-php#275]
Dear Ankit Pokhrel
Thanks for your great job in developing UPPY and TUS php.  I am trying to use these packages in  my project but  have problems in defining "dynamic upload path". I mean I want to define an specify path for each upload form (consider each user has its own upload folder)
How can I do that?
I will be so grateful if you would help me in this matter.
regards

**Comment by ankitpokhrel** [comment]
@imRezaAlie You can set upload path for each upload by setting upload path on creation request, which is the first request that is sent when you start the upload. See [this](https://github.com/ankitpokhrel/tus-php/issues/79#issuecomment-425192496).

**Comment by imRezaAlie** [comment]
Thanks Dear  @ankitpokhrel  .  I can Solve it...

**Comment by imRezaAlie** [comment]
`TusConfig::set(config_path('tus-server.php'), true);
            $server = new TusServer('redis');
            $userID = $server->getRequest()->header('userID');

            $baseDir =storage_path("app/assets/DtOrderFiles/".$userID);

            $uploadPath = $baseDir;

            $segment = $server->getRequest()->header('segment');

            // Handler
            if ($segment == 'avatar') {

                $uploadPath = $baseDir . '/LogFile/';
            }

            if (!is_dir($uploadPath)) {
                mkdir($uploadPath, 0777, true);
            }

            $server
                ->setApiPath('/tus')
                ->setUploadDir($uploadPath);
`
