### ISSUE TITLE
tus-server.upload.complete event is called multiple times for a single file

### ISSUE THREAD

**Issue by renepardon** [ankitpokhrel/tus-php#279]
**Describe the bug**
_tus-server.upload.complete_ event is called multiple times for a single file upload. I upload a huge file in multiple chunks during a unit test:

```
$bytesUploaded = $client->upload(1000000);
$bytesUploaded = $client->upload(1000000);
$bytesUploaded = $client->file($path, $name)->upload();
```

**To Reproduce**
https://gist.github.com/renepardon/e414fe2b3bbaa6e244662932d388790b

**Expected behavior**
The complete event should only be triggered once for an upload if the upload finishes "completely" not on complete for every chunk which was uploaded.

**Screenshots**
When debugging with _Log::_ facade, i see the following:
![Bildschirmfoto 2020-06-22 um 15 47 06](https://user-images.githubusercontent.com/945323/85295114-c5d39900-b49f-11ea-9bcf-c8e4bf5a50d9.png)
![Bildschirmfoto 2020-06-22 um 15 47 14](https://user-images.githubusercontent.com/945323/85295120-c835f300-b49f-11ea-9cf3-4d75c57769a2.png)

**Additional context**
The setup is a laravel application

**Comment by renepardon** [comment]
**tus-server.upload.merged** event is never called

**Comment by ankitpokhrel** [comment]
@renepardon `tus-server.upload.merged` event is only emitted when using [concatenation extension](https://tus.io/protocols/resumable-upload.html#concatenation). For that, you need to provide the parts of the file you want to upload and merge them at the end. You can take [this example](https://github.com/ankitpokhrel/tus-php/blob/master/example/partial/partial.php#L24-L32) as a reference.


> ```
> $bytesUploaded = $client->upload(1000000);
> $bytesUploaded = $client->upload(1000000);
> $bytesUploaded = $client->file($path, $name)->upload();
> ```

In the above implementation you shared, you are sending a normal upload request so the `tus-server.upload.complete` event is emitted for each call to upload (3 times). While if you use concatenation request `tus-server.upload.merged` event is emitted once all chunks are merged successfully.

**Comment by renepardon** [comment]
Ok, thx!
I'll have a look at this.
