### ISSUE TITLE
Ability to get the Response object after $server->serve()

### ISSUE THREAD

**Issue by lionelhg** [ankitpokhrel/tus-php#29]
It would be very nice to tell the server not send the response and instead return the Response object. Even though the sever has the method getResponse(), is imposible to get it because the script ends due to calling exit().

It would be better to allow serve() to be silent and then grab the response. Here are some ideas:

`$response = $server->serve(false); // $send = false`

`$response = $server->handle();` or `$response = $server->process();`

`$server->serve(false); // $send = false`
`$response = $server->getResponse();`

Thank you for the great work.

**Comment by ankitpokhrel** [comment]
@lionelhg good point, need to think about how to achieve this though.

**Comment by ankitpokhrel** [comment]
Fixed in #30
