### ISSUE TITLE
Uppy Dropbox companion

### ISSUE THREAD

**Issue by shivapoudel** [ankitpokhrel/tus-php#299]
It's just a question, will we be able to create endpoints for Drive, Dropbox, etc auth for Uppy using this library, or is there any alternatives to make those endpoints in PHP rather than in node environment.

Thanks in advance!

**Comment by ankitpokhrel** [comment]
Hi @shivapoudel, I am not sure If I understood you correctly, but it seems like you want to upload files to third party providers like Drive/Dropbox using the tus-protocol. 

`tus-php` doesn't support this out of the box. However, many cloud providers implement a PHP [streamWrapper](https://www.php.net/manual/en/class.streamwrapper.php) interface that enables us to store and retrieve data from these providers using built-in PHP functions. An example of a similar approach to upload files to S3 can be found [here](https://github.com/ankitpokhrel/tus-php#cloud-providers).

If the provider you want to use doesn't have a streamWrapper interface implemented, you will have to upload files in 2 steps.

- Upload the file to your server using `tus-php`.
- Once the upload is done, [tus-server.upload.complete](https://github.com/ankitpokhrel/tus-php#events) event is fired. You can [listen to this event](https://github.com/ankitpokhrel/tus-php#responding-to-an-event) to push the file to Drive/Dropbox.

   ```php
   $server->event()->addListener('tus-server.upload.complete', function (\TusPhp\Events\TusEvent $event) {
       $fileMeta = $event->getFile()->details();
  
       // Push files to third-party providers.
   });
   ```

If you are using node there is a [tus node-server](https://github.com/tus/tus-node-server) available and you can use a similar approach to upload files to third party providers.

**Comment by shivapoudel** [comment]
@ankitpokhrel I am trying to implement an Uppy file uploader where the plugin itself acts as the companionURL either with RestApi or any alternatives. Just like `tus` if there was any Uppy companion library for PHP than that would be useful for integrating into WP.

I have spent several hours to configure WP Rest API for Uppy but all the auth redirects and callbacks are a bit heavy to handle in PHP.

**Comment by ankitpokhrel** [comment]
@shivapoudel I think I got what you are trying to say.

[tus](https://tus.io/) and [companion](https://uppy.io/docs/companion) are two different things and you cannot configure companion in PHP using this library.

`companion` acts as a bridge between third party upload source and your server while `tus` is an open protocol for resumable uploads. To use `tus` with `companion` using the [`COMPANION_UPLOAD_URLS`](https://uppy.io/docs/companion/#Options) (or `uploadUrls` option) should be enough but companion needs to be configured separately.
