### ISSUE TITLE
Getting 400 error when use & character in file name

### ISSUE THREAD

**Issue by sachin8600** [ankitpokhrel/tus-php#315]
We got 400 error when upload file using uppy for specific file having & character in the name

If remove & character file upload successful. But if add & character file upload got 400 bad request error.

**Comment by ankitpokhrel** [comment]
Characters like `../`, `"`, `'`, `&`, `/`, `\\`, `?`, `#`, `:` are not allowed in the file name for security reasons.

**Comment by sachin8600** [comment]
Thanks for reply.

Currently we changed code in the uppy side

onBeforeFileAdded:(currentFile, files) => {
      const modifiedFile = {
        ...currentFile,
        name: currentFile.name.replace("&", "and")
      }
      return modifiedFile
    }

So atleast file must be uploaded
