### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by xtezza** [ankitpokhrel/tus-php#319]
> **Note:** Please report any security issues directly to hello [at] ankit.pl
 
**Describe the bug**
There is an error when trying to install V1.2 via composer.
the error message is : 

Problem 1
    - Conclusion: don't install ankitpokhrel/tus-php v1.2.3
    - Conclusion: don't install ankitpokhrel/tus-php v1.2.2
    - Conclusion: don't install ankitpokhrel/tus-php v1.2.1
    - Conclusion: remove guzzlehttp/guzzle 7.2.0
    - Installation request for ankitpokhrel/tus-php ^1.2 -> satisfiable by ankitpokhrel/tus-php[v1.2.0, v1.2.1, v1.2.2, v1.2.3].
    - Conclusion: don't install guzzlehttp/guzzle 7.2.0
    - ankitpokhrel/tus-php v1.2.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0) -> satisfiable by guzzlehttp/guzzle[7.2.0].

I've tried ti install V2.1 but there is an error to : 

Problem 1
    - Installation request for ankitpokhrel/tus-php ^2.1 -> satisfiable by ankitpokhrel/tus-php[v2.1.0].
    - Conclusion: remove symfony/process v3.4.45
    - Conclusion: don't install symfony/process v3.4.45
    - ankitpokhrel/tus-php v2.1.0 requires symfony/console ^5.0 -> satisfiable by symfony/console[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8].
    - symfony/console v5.0.0 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.1 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.10 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.11 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.2 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.3 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.4 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.5 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.6 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.7 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.8 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.0.9 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.0 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.1 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.2 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.3 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.4 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.5 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.6 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.7 conflicts with symfony/process[v3.4.45].
    - symfony/console v5.1.8 conflicts with symfony/process[v3.4.45].
    - Installation request for symfony/process (locked at v3.4.45) -> satisfiable by symfony/process[v3.4.45].

**Additional context**
I use Codeigniter4
PHP version is 7.2.31

What is the solution to install ???
Thx

**Comment by ankitpokhrel** [comment]
@xtezza `v1.*` is not yet updated to use guzzle 7. And you cannot use V2 since you are using Symfony 3 packages. I will try to make a new `v1.*` release to support guzzle 7.

**Comment by xtezza** [comment]
I've found the solution, i've removed first  kriswallsmith/assetic, i've get symfony/console and that's fine !
Thanks for your response.
I close the issue.
