### ISSUE TITLE
Multiple CORS headers not allowed

### ISSUE THREAD

**Issue by jappe999** [ankitpokhrel/tus-php#322]
**Is your feature request related to a problem? Please describe.**
The example code for Laravel/Lumen uses both the `serve` and `send` methods and creates sets the headers twice. Because of this our file upload didn't work and Firefox warned that [multiple CORS headers are not allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMultipleAllowOriginNotAllowed).
![image](https://user-images.githubusercontent.com/10500389/99961889-7f0c0700-2d8f-11eb-9617-eeaa344bb1c2.png)

We use Laravel 6.0 and the file upload endpoint is guarded by the api middleware.

**Describe the solution you'd like**
I'd like a note at step 3 on the [Wiki page for Laravel & Lumen Integration ](https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration) stating that it might be possible that the headers are duplicated. A solution is to omit the `send` method and directly return the object returned by the `serve` method.
```PHP
Route::any('/tus/{any?}', function () {
    return app('tus-server')->serve();
})->where('any', '.*');
```

**Comment by ankitpokhrel** [comment]
Thanks, I amended the doc. The `$response->send()` step is actually not requried.

**Comment by jappe999** [comment]
Thanks!
