### ISSUE TITLE
ErrorException: Undefined offset: 1 Request.php

### ISSUE THREAD

**Issue by ebrahimirad** [ankitpokhrel/tus-php#325]
Hello friends,
I got error sometimes on production when the user want to upload file.
Error Log Stack:
```
ErrorException: Undefined offset: 1 in vendor/ankitpokhrel/tus-php/src/Request.php:148
vendor/ankitpokhrel/tus-php/src/Request.php(121): TusPhp\Request->extractMeta()
vendor/ankitpokhrel/tus-php/src/Tus/Server.php(345): TusPhp\Request->extractFileName()
vendor/ankitpokhrel/tus-php/src/Tus/Server.php(276): TusPhp\Tus\Server->handlePost()
app/Classes/TusServerActions.php(51): TusPhp\Tus\Server->serve()
```

What is the problem?

**Comment by ankitpokhrel** [comment]
Hi @ebrahimirad It can happen if the `Upload-Metadata` header is not in the correct format. Is it possible to share what is in the `Upload-Metadata` header when you get this error? Also, please state info like the `tus-php` library version you are using, and are you using it for client/server/both?

From the tus protocol doc:

> The Upload-Metadata request and response header MUST consist of one or more comma-separated key-value pairs. The key and value MUST be separated by a space. The key MUST NOT contain spaces and commas and MUST NOT be empty.

**Comment by ebrahimirad** [comment]
`Upload-Metadata: filename 2YXYr9in2LHaqS5yYXI=,filetype`

**Comment by ebrahimirad** [comment]
Also it happen in the tus-server, when someone try to upload file on the server

**Comment by ankitpokhrel** [comment]
> Upload-Metadata: filename 2YXYr9in2LHaqS5yYXI=,filetype

@ebrahimirad sorry for the late response. I see that `filetype` doesn't contain any value which is incorrect. Please make sure that the metadata always has a key-value pair separated by a space.
