### ISSUE TITLE
How to response error and reject upload ?

### ISSUE THREAD

**Issue by hthanhbmt** [ankitpokhrel/tus-php#334]
I think in a project validation and notification are important because you cannot allow users to upload any file type e.g. file is too large, the file contains malicious code or file in a format that your application does not support.
But I did not find any guidance in the documentation you provided.
What is the best practice?
Can you give some code example response error and reject upload for me and someone who needs it?

I'm using Laravel 5.8 with ankitpokhrel/tus-php 1.3

**Comment by ankitpokhrel** [comment]
Hi @hthanhbmt, you should be able to do this with a [middleware](https://github.com/ankitpokhrel/tus-php#middleware). The example below shows a case where you can reject an upload if the user is not authenticated. Using a similar technique, you can validate file types.

```php
<?php

namespace Your\Namespace;

use TusPhp\Request;
use TusPhp\Response;
use TusPhp\Middleware\TusMiddleware;

class Authenticated implements TusMiddleware
{
    // ...

    /**
     * {@inheritDoc}
     */
    public function handle(Request $request, Response $response)
    {
        // Check if user is authenticated
        if (! $this->user->isLoggedIn()) {
            throw new UnauthorizedHttpException('User not authenticated');
        }

        $request->getRequest()->headers->set('Authorization', 'Bearer ' . $this->user->token());
    }

    // ...
}
```

**Comment by hthanhbmt** [comment]
I tried to throw an Exception just like you before but Uppy still trying to post request until uses up the numbers of trying.
The throwing Exception will respond HTML instead of JSON.
How to return JSON to display messages on Uppy?

**Comment by rajpt** [comment]
@hthanhbmt would like to know how are you doing this? I have similar situation where before file upload starts i need to make sure user is in the overall account limit, if it is then allow upload otherwise reject. In my application every user has total account upload limit say 2 GB. Thank you.
