### ISSUE TITLE
Wiki: Wordpress integration

### ISSUE THREAD

**Issue by lennartbader** [ankitpokhrel/tus-php#336]
The Wiki contains an error for the Wordpress integration explanation. 

In Step 8:

`$wp->query_vars['pagename']
`

should be:

`$wp->query_vars['name']
`

**Comment by ankitpokhrel** [comment]
I think this was changed in the recent WP version. I will update the docs accordingly. Thanks for reaching out.

**Comment by lennartbader** [comment]
#277 is most likely caused by this too.

**Comment by ankitpokhrel** [comment]
@lennartbader `pagename` seems to be working fine in WP5.5 & WP5.6. It might be that something else is interfering with the query var. Can you please try  with clean installation (no plugins and default theme) and see how it goes?
