### ISSUE TITLE
uploadUrl does not resolve to images when using file based caching

### ISSUE THREAD

**Issue by duerrsimon** [ankitpokhrel/tus-php#337]
I am using Uppy and I struggle to set the uploadUrl of the uploaded images correctly. 

The Tus Endpoint resides in the `/file-upload/` folder: 

`index.php`

```
require __DIR__ . '/vendor/autoload.php';
$server = new \TusPhp\Tus\Server();
$server->setApiPath('/files');

if (strtolower($server->getRequest()->method()) === 'post') {
    $baseDir    = __DIR__ . '/uploads/';
    $uploadPath = $baseDir . $server->getUploadKey();
    if ( ! is_dir($uploadPath)) {
        mkdir($uploadPath);
    }
    $server->setUploadDir($uploadPath);
}
// Send response
$response = $server->serve();
$response->send();
```
`.htaccess`
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^files/?(.*)?$ index.php?$1 [QSA,L]
```

File upload in Uppy works correctly and the files show up in the respective server directory. 
However, the uploadUrl in the response points to e.g `servername.com/file-upload/files/e38b5189-590c-4c8d-9e0f-79f6ef0892c` and not to `servername.com/file-upload/uploads/e38b5189-590c-4c8d-9e0f-79f6ef0892c/filename.jpg`. 

Any pointers on how to fix this? Is it a htaccess problem or do I need to alter my php code to overwrite the `uploadUrl` in the response that is returned to Uppy?

**Comment by ankitpokhrel** [comment]
Hi @duerrsimon, the upload URL is correct. You need to send a GET request to fetch that resource

```sh
$ curl http://servername.com/file-upload/files/e38b5189-590c-4c8d-9e0f-79f6ef0892c

# or, for binary output
$ curl http://servername.com/file-upload/files/e38b5189-590c-4c8d-9e0f-79f6ef0892c/get
```

**Comment by rizkhal** [comment]
It's possible to custom `uploadURL` using filename with path instead of uuid?

Let's say i uploading an image, when i access `http://servername.com/file-upload/files/e38b5189-590c-4c8d-9e0f-79f6ef0892c`
in the browser, it's just blank screen, when add `/get` it's automatic download the file
