### ISSUE TITLE
Docker Compose Up Failed

### ISSUE THREAD

**Issue by mvatansever** [ankitpokhrel/tus-php#35]
The docker solution of the project not working seamlessly.
I execute the command: **docker-compose up -d**

And the terminal say me to:
> Pulling tus-base (tus-php-base:latest)...
ERROR: pull access denied for tus-php-base, repository does not exist or may require 'docker login'

Can you give access of the docker hub repository?

**Comment by ankitpokhrel** [comment]
I am using local images. You need to run:
```
$ bin/docker.sh
```

This will build and run all images locally.
