### ISSUE TITLE
Deploy tus-php on laravel and apache server

### ISSUE THREAD

**Issue by sebasegovia01** [ankitpokhrel/tus-php#354]
**Problem:**
I have a problem when passing the code that runs locally with xampp, to a test server with apache. In local, the protocol works perfectly with the path: **http://127.0.0.1:8000/tus**  ,but in apache server i don't know how to deploy this, in test server i have: **https://myserverdomain.com:8000/tus** and give me the next error:

![image](https://user-images.githubusercontent.com/35777287/133182877-9514b23c-28ec-4bdf-be9a-4543dafe6b72.png)

This is my implementation of tus-php (it is exactly the same as the documentation) (working in local environment):

https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration

I just change the folder where the files are stored and im not using redis 

**TusServiceProvider.php:**

![image](https://user-images.githubusercontent.com/35777287/133183449-b6723e49-9a76-4342-a350-6e23b3bb81db.png)

**I'm using in composer:** 
ankitpokhrel/tus-php v2.1.2 
laravel/framework v7.30.4

**In npm and laravel-mix:**
tus-js-client@2.3.0

Please if you can help me guys to deploy this on the server I would appreciate it a lot 🙏🙏

**Comment by ankitpokhrel** [comment]
Hi @sebasegovia01, I see `ERR_CONNECTION_TIMED_OUT` error in the snapshot which typically means there is something wrong with your network connection or your server is timing out while trying to process the request. Please check your server logs to get a hint on what is causing the issue.

**Comment by sebasegovia01** [comment]
Hi, i reconfigure the path of tus, and now is: https://developer.whwdata.com/tus, but i have the next error: 500
![image](https://user-images.githubusercontent.com/35777287/134039297-dc52d924-38d1-4a1e-bc76-6aca7f5c4fdf.png)

More information about the error has been detailed below:

![image](https://user-images.githubusercontent.com/35777287/134039645-ad22461d-6561-426e-81d4-6c46d00c15dd.png)

The log is too long to copy here hahaha.

This is the .htaccess configuration what do i use:

![image](https://user-images.githubusercontent.com/35777287/134039769-39d2625d-6e01-40bb-b0b6-01b7da5277a5.png)

**Comment by sebasegovia01** [comment]
> Hi, i reconfigure the path of tus, and now is: https://developer.whwdata.com/tus, but i have the next error: 500
> ![image](https://user-images.githubusercontent.com/35777287/134039297-dc52d924-38d1-4a1e-bc76-6aca7f5c4fdf.png)
> 
> More information about the error has been detailed below:
> 
> ![image](https://user-images.githubusercontent.com/35777287/134039645-ad22461d-6561-426e-81d4-6c46d00c15dd.png)
> 
> The log is too long to copy here hahaha.
> 
> This is the .htaccess configuration what do i use:
> 
> ![image](https://user-images.githubusercontent.com/35777287/134039769-39d2625d-6e01-40bb-b0b6-01b7da5277a5.png)

I catch the error in laravel, I think it is write permissions error.

```
[2021-09-20 13:38:19] production.ERROR: mkdir(): Permission denied {"userId":120,"exception":"[object] (ErrorException(code: 0): mkdir(): Permission denied at /var/www/html/smart_traffic/vendor/ankitpokhrel/tus-php/src/Cache/FileStore.php:88)
[stacktrace]
```

**Comment by sebasegovia01** [comment]
Problem fixed, that was the problem:

production.ERROR: mkdir(): Permission denied {"userId":120,"exception":"[object] (ErrorException(code: 0): mkdir(): Permission denied at /var/www/html/smart_traffic/vendor/ankitpokhrel/tus-php/src/Cache/FileStore.php:88)
[stacktrace]

I grant the permissions to that folder and that's it working 💯

**Comment by samundra** [comment]
@sebasegovia01 Glad you resolved it 🎉

**Comment by Andi82ka** [comment]
I had the same problem and solved it also by giving write permission to vendor/ankitpokhrel folder in my laravel project. But I don't feel good with that. Is there an option to set the cache-folder to laravels storage cache?
