### ISSUE TITLE
PHP 8 support for V1

### ISSUE THREAD

**Issue by paugerhu** [ankitpokhrel/tus-php#359]
The V1 cannot be installed via composer on PHP 8, because the PHP 7 is required in composer.json.
Is it possible to add PHP 8 to the composer.json for V1?

**Comment by ankitpokhrel** [comment]
@paugerhu you need to upgrade to v2 if you want to use PHP8. Is there any specific reason that you want to use v1 with PHP8?

**Comment by paugerhu** [comment]
I use TUS in a Drupal project which is based on Symfony 4, so I can not use Symfony 5 which is a requirement for the V2. After the Dupal 10 has been released, I will be able to upgrade to TUS v2. I am currently ignoring platform requirement in composer to install TUS v1 l, but it is not the best solution.

**Comment by ankitpokhrel** [comment]
Apologies for late response! 

Symfony 5 requires PHP7.2 and tus-php v1 supports PHP7.1. So for compatibility reasons version was bumped.

I think for your case, you can maintain a fork with changes required for Symfony 5 support on V1. You can get an idea of the changes here https://github.com/ankitpokhrel/tus-php/compare/v1.3.1...v2.0.0

Let me know if that works for you!
