### ISSUE TITLE
Send to CloudFlare

### ISSUE THREAD

**Issue by tiagomatosweb** [ankitpokhrel/tus-php#361]
I want to upload a file with resume capability to Cloudflare. However, I want to send files to CloudFlare from my backend.

Something like my app -> my backend -> CloudFlare?

So, I wonder if there is a way to do that and avoid uploading files to my own server and then upload again to CloudFlare. 

I believe it would be similar approach to the AWS S3 stream wrapper example in the doc, but for CloudFlare.

**Comment by ankitpokhrel** [comment]
Hi @tiagomatosweb, yes you need to follow similar approach with the stream wrapper API. Direct upload to cloud providers is not implemented at the moment.

**Comment by paulocastellano** [comment]
@tiagomatosweb you made it? If possible can share the code with me?
