### ISSUE TITLE
Update the filename when save file

### ISSUE THREAD

**Issue by prabhatjhaba** [ankitpokhrel/tus-php#370]
Hi
Can we have a example where we can change the name of the file when it get saved, right it keeps original file name from the request header when it get saved. I do not see any method that can change the file name. 

Thanks in advance.

**Comment by ankitpokhrel** [comment]
@prabhatjhaba you can use [events](https://github.com/ankitpokhrel/tus-php#events) to update the filename once it get uploaded.

```php
$server->event()->addListener('tus-server.upload.complete', function (\TusPhp\Events\TusEvent $event) {
    $fileMeta = $event->getFile()->details();
     
    // Rename your file here.
});
```
