### ISSUE TITLE
CakePHP implementation issue

### ISSUE THREAD

**Issue by wilsmex** [ankitpokhrel/tus-php#371]
Following along with the sample CakePHP implementation (I'm using latest CakePHP 4), but I get the following error when hitting my /tus endpoint

'Controller actions can only return ResponseInterface instance or null. Got Symfony\Component\HttpFoundation\Response instead.'

Any ideas?

**Comment by ankitpokhrel** [comment]
Hi @wilsmex, the documentation is possibly outdated however it gives you the idea about the integration. 

I haven't worked with CakePHP for a long time but looking at the error it looks like CakePHP controllers now requires [PSR-7 ](https://www.php-fig.org/psr/psr-7/)compatible response object. But this package returns [symfony HTTPFoundation Response](https://symfony.com/doc/current/components/http_foundation.html#response).

So something like this should do the trick for now (**untested**).

```php
<?php

// composer require symfony/psr-http-message-bridge

namespace App\Controller;

use Cake\Controller\Controller;
use TusPhp\Tus\Server as TusServer;
use Nyholm\Psr7\Factory\Psr17Factory;
use Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory;

class TusController extends Controller
{
    /**
     * Create tus server.
     *
     * @return Psr\Http\Message\ResponseInterface
     */
    public function server()
    {
        $server = new TusServer('redis');

        $server
            ->setApiPath('/tus')// tus server endpoint
            ->setUploadDir(WWW_ROOT . 'uploads'); // upload dir

        $symfonyResponse = $server->serve();

        $psr17Factory   = new Psr17Factory();
        $psrHttpFactory = new PsrHttpFactory($psr17Factory, $psr17Factory, $psr17Factory, $psr17Factory);
        $psrResponse    = $psrHttpFactory->createResponse($symfonyResponse);

        return $psrResponse;
    }
}

```
