### ISSUE TITLE
problem with ios client (TUSKit), incorrect Upload-Metadata is being sent

### ISSUE THREAD

**Issue by sjay23** [ankitpokhrel/tus-php#378]
Faced such a problem. the php and js client works well and sends the correct data to Upload-Metadata.
When I use the ios client, the data is sent like this
```
filename MzgxREJGRkQtRkM0MS00MUNELTkwNjgtNUIyOTNBMjU4QUEy, filetype YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFt - is not correct
```
And a 500 error is thrown. Because of the gap. Is there a way to fix this. 
Because without a space everything works correctly.
```
filename MzgxREJGRkQtRkM0MS00MUNELTkwNjgtNUIyOTNBMjU4QUEy,filetype YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFt - is correct
```

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/3989843/152167396-67418496-acf8-4e58-aab4-ce5eee144bc2.png)
![image (3)](https://user-images.githubusercontent.com/3989843/152167900-8ef7de98-51c1-48c9-b05f-88c2276a2adc.png)

I added an example of debugging this parameter in different situations.

**Comment by ankitpokhrel** [comment]
@sjay23 you can use `2.2-dev` to try out the fix.

**Comment by sjay23** [comment]
@ankitpokhrel hi, yes it's ok. thank you

**Comment by kliperjk** [comment]
@ankitpokhrel When can i expect release with this fix? Best regards!
