### ISSUE TITLE
Is it possible to customize the endpoints?

### ISSUE THREAD

**Issue by dausruddin** [ankitpokhrel/tus-php#381]
Hi.

I am trying to implement this into an existing project.
The project is using a direct file to upload , `upload.php`. But from what I see in installation, I need to configure path for the endpoints in webserver.

I know I can change the endpoints in client to `upload.php`, but will there be any issues? 

Thank you.

**Comment by ankitpokhrel** [comment]
Hi @dausruddin, you can pass base url of the server when setting up the client as mentioned [here](https://github.com/ankitpokhrel/tus-php#client). There shouldn't be any issue as long as the server is working fine.
