### ISSUE TITLE
patch: array access on null in case key expires

### ISSUE THREAD

**Issue by jmglsn** [ankitpokhrel/tus-php#388]
**Describe the bug**
In case during a patch request the cache key expires, the code breaks.

**To Reproduce**
Just check line https://github.com/ankitpokhrel/tus-php/blob/main/src/Tus/Server.php#L501 and consider that `$this->cache->get($uploadKey)['expires_at']` fails as `$this->cache->get($uploadKey)` returns null.

This causes a `Trying to access array offset on value of type null`.

**Expected behavior**
- Maybe we should access `$meta` here once more?
- Or fail with `HTTP_GONE`?

Thank you :)

**Comment by ankitpokhrel** [comment]
Hi @jmglsn, there is a slight chance that the cache might expire before sending the response from patch request. The better option would be to fail with `HTTP_GONE`. Are you getting lots of `Trying to access array offset on value of type null` errors? This is not supposed to happen that often.

**Comment by jmglsn** [comment]
Hi @ankitpokhrel, that's true it's nothing that happens that often, as the possible frame to hit this is super small.
I also assume that HTTP_GONE would be the best response in that case.
