### ISSUE TITLE
Can't upload same name two different file. 

### ISSUE THREAD

**Issue by dipaksarkar** [ankitpokhrel/tus-php#402]
can't upload same same two different file. Suppose i have one file name with test.mp4 and same name another file in different location. If i uploaded on and trying to upload another then it's showing as completed.

**Comment by ankitpokhrel** [comment]
The file are compared based on their hash value generated from their contents. So if you have the exact same file with different name it is still the same file.

**Comment by dipaksarkar** [comment]
@ankitpokhrel It was two different file of same name.

**Comment by ankitpokhrel** [comment]
@dipaksarkar The upload is determined by the `Upload-Key` which the client can pass in request header. A unique key is generated if this key is not available in the headers. I assume your client is sending same upload key if the filename is same. Could you check the `Upload-Key` header in your requests?
