### ISSUE TITLE
redis store sometimes returns $contents without key expires_at

### ISSUE THREAD

**Issue by jmglsn** [ankitpokhrel/tus-php#404]
Hey,

I noticed that under some circumstances the array `$contents` is missing the key `expires_at` right over here:

https://github.com/ankitpokhrel/tus-php/blob/f50852b85b513ec5589f7871d4ca59d7c1c3ad8d/src/Cache/RedisStore.php#L60

It's showing up super seldom but maybe worth a short investigation.

Thank you!

**Comment by jmglsn** [comment]
FYI: Still seeing this error from time to time...

**Comment by ankitpokhrel** [comment]
I think this is related to #376, some details regarding this behavior are in the comments.

**Comment by jmglsn** [comment]
Thank you @ankitpokhrel – I'll cross check that once more, maybe I missed a link and the cache is varnished during the request.
