### ISSUE TITLE
Predis\Connection\ConnectionException

### ISSUE THREAD

**Issue by jessice-ai** [ankitpokhrel/tus-php#405]
1、确定redis可以使用。
2、代码
$server   = new \TusPhp\Tus\Server('redis');
        
**$response = $server->serve();**   #程序到这里，报错了 Predis\Connection\ConnectionException
        
$response->send();

exit(0); // 退出当前 PHP 进程

**Comment by ankitpokhrel** [comment]
`ConnectionException` usually implies that the server cannot connect to the redis instance. Make sure that the connection details are set correctly. You can use `REDIS_HOST`, `REDIS_PORT` and `REDIS_DB` env in your server to override redis settings for both server and client.

Note: Please use the issue template with as much details as possible when creating a issue.
