### ISSUE TITLE
Do you plan to release a v2.2.2 compatible with Predis v2 ?

### ISSUE THREAD

**Issue by shulard** [ankitpokhrel/tus-php#407]
Hello !

I'm using your awesome server on one of my project. Today I tried to upgrade the dependencies. We are using `predis/predis` on our side and we saw that we can't use v2 because `tus-php` last version is not compatible with it.

I saw that a change was merged in june to make the library compatible. Can you tag a new minor version ?

Thanks !

**Comment by ankitpokhrel** [comment]
Hi @shulard, new release is available now: [v2.3.0](https://github.com/ankitpokhrel/tus-php/releases/tag/v2.3.0)

**Comment by shulard** [comment]
Awesome thank you !
