### ISSUE TITLE
Continue file upload from different browser and device

### ISSUE THREAD

**Issue by rajpt** [ankitpokhrel/tus-php#409]
I have successfully implemented uppy([tus-js-client](https://github.com/tus/tus-js-client)) and tus-php, it works great and so impressed with the resumable functionality.

Other day i was testing:

1. Start upload on my iMAC using google chrome for file `my-upload-audio.mp3`
2. Pause the upload
3. User my MACBOOK PRO use Firefox and select the same file `my-upload-audio.mp3` to upload
4. Upload started but did not resume where it was paused on my iMAC

Not sure is it even possible to achieve what i am trying to do with current implementation? If so please provide some directions how to implement it?

Otherwise would be good to add this feature.

Thank you

**Comment by mbaumgartl** [comment]
The default implementation stores the upload urls using [Web Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) (when run in the browser). But you can implement an [interface](https://github.com/tus/tus-js-client/blob/master/docs/api.md#urlstorage) to share urls between browsers (e.g. by using web service).
