### ISSUE TITLE
Possible bug or configuration issue?

### ISSUE THREAD

**Issue by agbandini** [ankitpokhrel/tus-php#431]
> **Note:** Please report any security issues directly to hello [at] ankit.pl
 
**Describe the bug**
I am using this library with Uppy for uploading large files. After a few days of usage (it's heavily utilized, and the server receives many requests per day), the response times of the tus server endpoint have increased by several seconds for each request, and this happens even when there is no server traffic. My question is whether the library uses a cache or sessions that need optimization?

**Comment by agbandini** [comment]
I return on this topic because I think that probably to solve this problem is necessary to clean the unfinished uploads directory. I see in the project page that is present the command ./vendor/bin/tus tus:expired to do this. But I want to ask: someone can tell me the cache phisical path for a server setted with the 'file' cache adpter? I need to know that. Please, need help!! thank you

**Comment by netomarchiori** [comment]
@agbandini I believe Its within the vendor folder, look for /vendor/ankitpokhrel/tus-php/.cache

**Comment by agbandini** [comment]
yes. Exactely I found it. Thank you
