### ISSUE TITLE
[Uppy Integration] Progress bar reaches 100% instantly

### ISSUE THREAD

**Issue by ankitpokhrel** [ankitpokhrel/tus-php#44]
Progress bar instantly reaches 100% usually in local setup when using uppy with tus-php-server. There is a long pause afterwards while the file is being uploaded.

**Comment by karan-levaral** [comment]
I am also facing this issue, I think in Uppy server they are using socket to show the actual progress

**Comment by AurelienMendes** [comment]
I am also facing this issue but only when uploading many files in parallel.
But when files are processed sequentially (limit: 1 in uppy.tus) then the progress bar is correctly filed.

**Comment by marveloo** [comment]
I assume this is because there is no `fflush()` call after each `fwrite()` call.

**Comment by peiweijianphp** [comment]
My operating environment is docker + php7.2 + redis5  and  The client uses uppy.js  
My problem is:   When the upload progress bar is less than 100%, the offerkey of tus PHP response is' ', so every time you click pause, it will start from 0. When the upload progress is 100%, the offerkey in redis will change, the file will be merged, and the progress bar of uppy.js is 100%. When the uploaded file is large, the client will have to wait

**Comment by peiweijianphp** [comment]
![bug](https://user-images.githubusercontent.com/20853718/75839443-ccaca200-5e03-11ea-9943-a8f3be4073d3.png)

**Comment by ankitpokhrel** [comment]
Apparently, this happens because of [fastcgi_request_buffering](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_request_buffering) option in Nginx. 

When the buffering is enabled, the entire request body is read from the client before sending the request to a FastCGI server. If you are using Nginx, consider disabling `fastcgi_request_buffering` for resumable uploads. More info [here](https://github.com/ankitpokhrel/tus-php#nginx).
