### ISSUE TITLE
Resumable File Upload using API

### ISSUE THREAD

**Issue by HinaSharma1988** [ankitpokhrel/tus-php#53]
I need to do resumable file uploading using REST API (Laravel), 
API will be consumed by Android APP.
Please Suggest.

**Comment by ankitpokhrel** [comment]
@HinaSharma1988 you can setup server in Laravel as explained in [this doc](https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration). After you setup the server, following endpoints will be available to you.

```
# Gather information about server's current configuration
OPTIONS /files

# Check if the given upload is valid
HEAD /files/{upload-key}

# Create a new upload
POST /files

# Resume upload created with POST
PATCH /files/{upload-key}

# Delete the previous upload
DELETE /files/{upload-key}
```

Now either you can use [tus-android-client](https://github.com/tus/tus-android-client) (recommended) or manually send request to these endpoints to upload your file.

**Comment by Yangwendaxia** [comment]
@ankitpokhrel I need to do resumable file uploading using REST API (Laravel),
API will be consumed by browser。 After I setting up server in Laravel as you mentioned , how should I implement the client code ?
