### ISSUE TITLE
[Feature request] Add setCacheDir method in AbstractTus.php

### ISSUE THREAD

**Issue by terrylinooo** [ankitpokhrel/tus-php#55]
I meet permission problem so I have to define the cache dir for my app, however I found setCacheDir is defined in FileStore.php, is it possible to add setCacheDir method in AbstractTus.php?

Thanks.

**Comment by terrylinooo** [comment]
Or change the $cache variable from protected to public, 
```
    public $cache;
```
And I can use the setCacheDir method from $cache object
```
$client->cache->setCacheDir($this->cacheDir);
```

**Comment by ankitpokhrel** [comment]
You can do 
```php
$client->getCache()->setCacheDir($this->cacheDir)
```

**Comment by terrylinooo** [comment]
Thank you
