### ISSUE TITLE
Advanced Server

### ISSUE THREAD

**Issue by japheth-waswa** [ankitpokhrel/tus-php#57]
Great library,i have been able to get it up and running,though i need more functionality on the server ie
1.Returns/extract the size of file uploaded ie for each partial request
2.Returns/Extract the location of the uploaded file and the file name
The above two must be able to be done on the server side.
Thanks in advance.

**Comment by ankitpokhrel** [comment]
@japheth-waswa you can get size and path from cache

```php
$server->getCache()->get($key);
```

**Comment by japheth-waswa** [comment]
Thanks. on the server side, how can I add additional parameters on the
response to client ie I wanna return the total size uploaded on each
request

**Comment by ankitpokhrel** [comment]
The response header contains `Upload-Offset` which is the sum of the offset before the `PATCH` request and the number of bytes received and processed or stored during the current `PATCH` request. To get the header you can do something like this:

```php
$uploadedBytes = $server->getRequest()->header('Upload-Offset');
```

**Comment by japheth-waswa** [comment]
Thanks lemme try them
