### ISSUE TITLE
Cannot read file, when using file based cache

### ISSUE THREAD

**Issue by tomeroto** [ankitpokhrel/tus-php#77]
I just get an error like show on the picture below:

[CLICK HERE TO SHOW SCREEN SHOOT](https://image.ibb.co/kQDkCU/error_resumeable.png)

I use Macbook Pro for development, and using MAMP.

**Comment by ankitpokhrel** [comment]
@tomeroto this looks like a permission issue in your setup, nothing to do with the package

**Comment by tomeroto** [comment]
I was set permission folder "/Applications/MAMP/tmp/php/" to 777 and its still not working.
