### ISSUE TITLE
Regarding saving the files into sub folders

### ISSUE THREAD

**Issue by shravanthanvi** [ankitpokhrel/tus-php#79]
Hi
Want to have an example in php where in want to save the files into the subfolder based on key generated

**Comment by ankitpokhrel** [comment]
@shravanthanvi You can change `server.php` from [examples](https://github.com/ankitpokhrel/tus-php/blob/master/example/server.php) to the following. It will save all new uploads in a separate folder.

```php
<?php

require __DIR__ . '/../vendor/autoload.php';

$server = new \TusPhp\Tus\Server('redis');

if (strtolower($server->getRequest()->method()) === 'post') {
    $baseDir    = __DIR__ . '/../uploads/';
    $uploadPath = $baseDir . $server->getUploadKey();

    if ( ! is_dir($uploadPath)) {
        mkdir($uploadPath);
    }

    $server->setUploadDir($uploadPath);
}

$response = $server->serve();

$response->send();

exit(0); // Exit from current PHP process.
```

**Comment by shravanthanvi** [comment]
Thank you will try it and let you know

**Comment by muratgozel** [comment]
As a uppy.js user, I send a path along with the upload request and placing the file wherever I want:
```php
if (strtolower($server->getRequest()->method()) === 'post') {
  $upload_path = MEDIA_ROOT . $server->getRequest()->extractMeta('folder');

  mkdir($upload_path, 0770, true);
  
  $server->setUploadDir($upload_path);
}
```

**Comment by lwahonen** [comment]
> 

This does not work with the chunked upload example

**Comment by lwahonen** [comment]
> @shravanthanvi You can change server.php from [examples](https://github.com/ankitpokhrel/tus-php/blob/master/example/server.php) to the following. It will save all new uploads in a separate folder.

This does not work with the chunked upload example. Your upload folder is left with just three chunks, the original file does not get reassembled
