### ISSUE TITLE
Using it under slim

### ISSUE THREAD

**Issue by shravanthanvi** [ankitpokhrel/tus-php#80]
Hi 

Any plans to support this under slim3 framework

**Comment by ankitpokhrel** [comment]
@shravanthanvi The package is framework agnostic, that means, you can use it with any php framework you choose to work with. You just need to prepare server by following the [documentations](https://github.com/ankitpokhrel/tus-php) and taking ideas from [framework integrations doc](https://github.com/ankitpokhrel/tus-php/wiki).
