### ISSUE TITLE
Importance of handleGet() as a file download?  Mirror behavior to handleHead()?

### ISSUE THREAD

**Issue by drastik** [ankitpokhrel/tus-php#86]
The Symfony2 PHP framework silently transforms all `HEAD` requests into `GET`.
https://github.com/symfony/symfony/issues/22028

This affects Drupal 8, as well as Laravel I'm sure:
https://www.drupal.org/project/drupal/issues/2752325

I don't know the stats, but between Drupal, Laravel, and Symfony itself.. this affects a substantial group of PHP projects.

What this causes is if you try to resume an upload, it attempts a few times, and then gives up.  This is because the `HEAD` is getting transformed into a `GET` request in the background (you can't see this in the request/response traffic, it still says `HEAD`).  Then the response to your TUS client (e.g. Uppy) is `tus-php` trying to provide a file download, instead of the proper `HEAD` headers.

**Comment by drastik** [comment]
@ankitpokhrel  @samundra 

Do you guys have any thoughts here?
It would be great if Symfony were to fully implement `HEAD` requests, but there have been many arguments for it in the past, and they were all shot down.  I don't know what the chances are of Symfony doing so, but I put in the feature request regardless.

**Comment by samundra** [comment]
Changing HEAD request to GET is definitely not desired. However, lets verify the changes needed for HEAD request to implement it in Symfony Request/Response. But we have to identify its impact on the project. Waiting for thoughts from @ankitpokhrel

**Comment by ankitpokhrel** [comment]
File download in `GET /files/<hash>` request is not a part of the tus specification. I would propose to move current file download endpoint to `GET /files/<hash>/get` and treat `GET /files/<hash>` same as HEAD request.

I am open for other ideas.

**Comment by samundra** [comment]
@ankitpokhrel I think we should try to implement what current tus-servers have implemented for the download request.

The solution that you proposed could work as custom solution for download extending on top of official tus server implementation. 

I think we should implement the custom solution that are already in use by most tus-servers.

**Comment by ankitpokhrel** [comment]
Changed in #87
