### ISSUE TITLE
TusClient is missing required headers

### ISSUE THREAD

**Issue by richard-keller** [ankitpokhrel/tus-php#91]
I'm currently trying to use tus-php to upload to [CloudFlare Stream](https://developers.cloudflare.com/stream/getting-started/uploading-command-line/). It looks like tus-php doesn't include all the standard required headers that the Tus protocol requires, and CloudFlare ends up giving an obscure error, and doesn't upload the file successfully.

Is there any way to output debug information so that I can see the contents of the HTTP request (including all headers) so that I can debug further?

I've considered intercepting the traffic using Wireshark, but CloudFlare uses HTTPS, which makes this rather difficult.

**Comment by ankitpokhrel** [comment]
@richard-keller you can pass `['debug' => true]` to guzzle options to [debug requests](http://docs.guzzlephp.org/en/stable/request-options.html#debug) after #90 is merged.

> It looks like tus-php doesn't include all the standard required headers that the Tus protocol requires

Can you be more specific on what headers are missing?

**Comment by richard-keller** [comment]
When sending a HEAD request, the header **must** contain a `Tus-Resumable` field which specifies the Tus version. As far as I can see, tus-php isn't sending the Tus version header. The request should look like this:

```
HEAD /files/24e533e02ec3bc40c387f1a0e460e216 HTTP/1.1
Host: tus.example.org
Tus-Resumable: 1.0.0
```

Additionally, when sending a PATCH request, the header must contain the `Upload-Offset` and `Tus-Resumable` fields. As far as I can see, tus-php isn't sending these.

From the protocol documentation:

`The Tus-Resumable header MUST be included in every request and response except for OPTIONS requests. The value MUST be the version of the protocol used by the Client or the Server.
`

`The Upload-Offset request and response header indicates a byte offset within a resource. The value MUST be a non-negative integer.
`







https://tus.io/protocols/resumable-upload.html#core-protocol
