### ISSUE TITLE
Throwing 404 errors in Laravel 

### ISSUE THREAD

**Issue by alexandrelgy** [ankitpokhrel/tus-php#93]
Your API seems great ! But i've been scratching my head for a few days now to integrate it. I'm still a beginner in Laravel and in php in general  but it seems that after following all your integration process (I found it very clear), I guess it throws 405 error at the upload stage.

I already included csrf in the header request. 

[Error message.txt](https://github.com/ankitpokhrel/tus-php/files/2501630/Error.message.txt)

Ever encountered this issue before ? 
Help would be much appreciated ! :)

**Routes**
```

//Tus routes
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');


Route::any('/files/{any?}', function () {
    $response = app('tus-server')->serve();

    return $response->send();
})->where('any', '.*');

Route::get('test', function (){
	return view('test');
});
Route::post('verify', 'TusController@TusFile');
Route::post('upload', 'TusController@UploadTus');

```

**Controller**

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use TusPhp\Exception\FileException;
use TusPhp\Exception\ConnectionException;
use GuzzleHttp\Exception\ConnectException;
use TusPhp\Exception\Exception as TusException;
use GuzzleHttp\Client;
require '/Users/fabrique/code/dancenote/vendor/autoload.php';




class TusController extends Controller
{

/**
 * Uploads files in 5mb chunk.
 */
public function TusFile () {


$client = new \TusPhp\Tus\Client('http://dancenote.test/tus');

// Alert: Sanitize all inputs properly in production code
if ( ! empty($_FILES)) {
    $status    = 'new';
    $fileMeta  = $_FILES['tus_file'];
    $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

    try {
        $offset = $client->setKey($uploadKey)->file($fileMeta['tmp_name'])->getOffset();

        if (false !== $offset) {
            $status = $offset >= $fileMeta['size'] ? 'uploaded' : 'resume';

        } else {
            $offset = 0;
        }
        echo json_encode([
            'status' => $status,
            'bytes_uploaded' => $offset,
            'upload_key' => $uploadKey,
        ]);
    } catch (ConnectException $e) {
        echo json_encode([
            'status' => 'errorconnect',
            'bytes_uploaded' => -1,
        ]);
    } catch (FileException $e) {
        echo json_encode([
            'status' => 'resume',
            'bytes_uploaded' => 0,
            'upload_key' => '',
        ]);
    }
} else {
    echo json_encode([
        'status' => 'error',
        'bytes_uploaded' => -1,
    ]);
}

}

public function UploadTus() {
	$client = new \GuzzleHttp\Client(['base_uri'=>'http://dancenote.test/tus', 'debug'=> true);
	// Alert: Sanitize all inputs properly in production code
	if ( ! empty($_FILES)) {
	    $fileMeta  = $_FILES['tus_file'];
	    $uploadKey = hash_file('md5', $fileMeta['tmp_name']);
	    try {
	        $client->setKey($uploadKey)->file($fileMeta['tmp_name'], time() . '_' . $fileMeta['name']);
	        $bytesUploaded = $client->upload(5000000); // Chunk of 5 mb
	        echo json_encode([
	            'status' => 'uploading',
	            'bytes_uploaded' => $bytesUploaded,
	            'upload_key' => $uploadKey
	        ]);
	    } catch (ConnectionException | FileException | TusException $e) {
	        echo json_encode([
	            'status' => 'error',
	            'bytes_uploaded' => -1,
	            'upload_key' => '',
	            'error' => $e->getMessage(),
	        ]);
	    }
	} else {
	    echo json_encode([
	        'status' => 'error',
	        'bytes_uploaded' => -1,
	        'error' => 'No input!',
	    ]);

}
}
}
```

**Comment by ankitpokhrel** [comment]
Ping @DrudgeRajen

**Comment by DrudgeRajen** [comment]
@alexandrelgy Checked your error.txt file. 
```
 "message": "Client error: `SETKEY http://dancenote.test/7e80d1faddb9611c4d82e21eed1bb68d` resulted in a `404 Not Found`
```
Instead of 405 there is 404 error. Can you please share what you have kept in your Service Provider (to run server) of  Laravel? Did you follow this [doc](https://github.com/ankitpokhrel/tus-php/wiki/Laravel-&-Lumen-Integration) properly?

**Comment by alexandrelgy** [comment]
Yes I did followed this doc ! I might have missed something ? 
Then would 404 come from a route I did not register ? 

Here is the service provider : 

**Service Provider**
```

<?php

namespace App\Providers;

use TusPhp\Tus\Server as TusServer;
use Illuminate\Support\ServiceProvider;

class TusServiceProvider extends ServiceProvider
{
    // ...

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('tus-server', function ($app) {
            $server = new TusServer('redis');

            $server
                ->setApiPath('/tus') // tus server endpoint.
                ->setUploadDir(storage_path('app/public/uploads')); // uploads dir.

            return $server;
        });
    }

    // ...
}   

```

**Comment by DrudgeRajen** [comment]
@alexandrelgy  Just remove 
```
 ->setApiPath('/tus') // tus server endpoint.
``` 
this line from your service provider. 
And from your route
```
Route::any('/tus/{any?}', function () {
    $response = app('tus-server')->serve();
    return $response->send();
})->where('any', '.*');
```

and Replace
```
$client = new \TusPhp\Tus\Client('http://dancenote.test/tus');
```
with
```
$client = new \TusPhp\Tus\Client('http://dancenote.test/');
```
Let me know if doesn't work.

**Comment by alexandrelgy** [comment]
It seems like now the verify call does not work neither returning a 500 server error specifying 

message | Server error: `HEAD http://dancenote.test/files/a885eae6a4904422193a8a7584287c2b` resulted in a `500 Internal Server Error` response

**Comment by DrudgeRajen** [comment]
@alexandrelgy did you add ``` TusServiceProvider``` class in config/app.php?

**Comment by ankitpokhrel** [comment]
> message | Server error: `HEAD http://dancenote.test/files/a885eae6a4904422193a8a7584287c2b` resulted in a `500 Internal Server Error` response

@alexandrelgy you can find laravel logs in `storage/logs`. Please check the logs and try to figure out the issue first. We can't help unless you provide us enough info about the issue.

**Comment by alexandrelgy** [comment]
Sure I did add this App\Providers\TusServiceProvider::class.
I'll check the doc once again and let you know if I did everything right !
@ankitpokhrel I'll also check logs and let you know if I figure out what's wrong. 

Thanks for help to you both ! :)

**Comment by samundra** [comment]
@alexandrelgy In any case, Could you please share your log file that's generated in `storage/logs` folder for the problem you are facing?

**Comment by alexandrelgy** [comment]
Sure, here it is. I'm going to investigate it today and keep you updated. 

[laravel.log.txt](https://github.com/ankitpokhrel/tus-php/files/2504786/laravel.log.txt)

**Comment by samundra** [comment]
@alexandrelgy  As per your provided log file this line

```
[2018-10-23 06:35:25] local.ERROR: Connection refused [tcp://127.0.0.1:6379] \{"exception":"[object] (Predis\\\\Connection\\\\ConnectionException(code: 61): Connection refused [tcp://127.0.0.1:6379] at /Users/fabrique/code/dancenote/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
```

states that it was unable to connect to redis server when you tried to make request for the file.

**Comment by alexandrelgy** [comment]
Nice thanks @samundra & @DrudgeRajen seems to work now !
I've been debugging a few things but i'm facing a response like : 
Unable to open /directory/dancenote/storage/app/public/uploads/filnename.file_extension.

I'll investigate it tomorrow but if by any chance someone you have already faced the problem let me know ! :)

**Comment by samundra** [comment]
Is your file uploaded successfully to upload directory `/directory/dancenote/storage/app/public/uploads/filnename.file_extension` ?

**Comment by DrudgeRajen** [comment]
@alexandrelgy  For server you had set upload directory as 
```
->setUploadDir(storage_path('app/public/uploads'));
```
So, please be sure you have ```` uploads ```` directory at ```storage/app/public```

**Comment by alexandrelgy** [comment]
Forgot to create it. Directory was missing what a fool.
It seems to work (pause resume and so on).

Really thank you you've been great help !

**Comment by jammersonf** [comment]
I have the same problem. I already follow the strunctions on this post, but i'm still in problem

Error:
> "message": "Client error: `SETKEY http://dev.bembras.api/75247b51bd97d93cd0094978a29b194e` resulted in a `405 Method Not Allowed`

web.php
![image](https://user-images.githubusercontent.com/2231447/55675609-7786aa00-589b-11e9-9c6c-6899d8854111.png)

TusServiceProvider.php
![image](https://user-images.githubusercontent.com/2231447/55675613-82d9d580-589b-11e9-8e03-e5d8485d7d89.png)

UploadController.php
`public function UploadTus()
    {
        $client = new \GuzzleHttp\Client(['base_uri'=>'http://dev.bembras.api', 'debug'=> true]);
        // Alert: Sanitize all inputs properly in production code
        if (! empty($_FILES)) {
            $fileMeta  = $_FILES['tus_file'];
            $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

            try {
                $client->setKey($uploadKey)->file($fileMeta['tmp_name'], time() . '_' . $fileMeta['name']);
                $bytesUploaded = $client->upload(5000000); // Chunk of 5 mb
                echo json_encode([
                    'status' => 'uploading',
                    'bytes_uploaded' => $bytesUploaded,
                    'upload_key' => $uploadKey
                ]);
            } catch (ConnectionException | FileException | TusException $e) {
                echo json_encode([
                    'status' => 'error',
                    'bytes_uploaded' => -1,
                    'upload_key' => '',
                    'error' => $e->getMessage(),
                ]);
            }
        } else {
            echo json_encode([
                'status' => 'error',
                'bytes_uploaded' => -1,
                'error' => 'No input!',
            ]);
        }
    }`

The Verify method is responding ok, the problem is only on upload.
Sorry for my bad English

**Comment by alexandrelgy** [comment]
405 errors in Laravel are often linked with csrf security in Laravel.

I added an exception to my VerifyCsrfToken.php and it worked for me.
I do not know if it is or not a bad habit in term of system security for production code, but for local use it seems fine. If the problem does come from here i suggest to add csrf headers in your ajax request. 

    <?php

    namespace App\Http\Middleware;

    use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

    class VerifyCsrfToken extends Middleware
    {
        /**
         * The URIs that should be excluded from CSRF verification.
         *
         * @var array
         */
        protected $except = [
            '/verify',
            '/tus',
            '/tus/*',
            'files',
            'files/*',
 
            
                ];
    }

**Comment by jammersonf** [comment]
@alexandrelgy Really. I add o except and passed, but still with error.

`Client error: `POST http://dev.bembras.api/files` resulted in a `404 Not Found` response:\nNo input file specified.\n\n",`

I already put the /files on virtualhost
![image](https://user-images.githubusercontent.com/2231447/55761692-92415600-5a36-11e9-9e67-30abde89489a.png)

Also changed the `$client = new \GuzzleHttp\Client(['base_uri'=>'http://dev.bembras.api', 'debug'=> true]);` by `$client = new \TusPhp\Tus\Client('http://dev.bembras.api');`on Upload Method
