### ISSUE TITLE
Client is able to set ApiPath.

### ISSUE THREAD

**Issue by DrudgeRajen** [ankitpokhrel/tus-php#94]
Checked the code and found that Client can set the ```$apiPath```  and which  is in the abstract scope of two classes. i.e Server and Client both. 

From Abstract Class :
```
/** @var string */
    protected $apiPath = '/files';

/**
     * Set API path.
     *
     * @param string $path
     *
     * @return self
     */
    public function setApiPath(string $path) : self
    {
        $this->apiPath = $path;

        return $this;
    }
```
So, this means that php Client can set the server API path . Is this the right way? Isn't it vulnerable?

**Comment by samundra** [comment]
@DrudgeRajen Could you please leave a comment on why you decided to close this issue. It still looks like a valid point and for some reason you decided you close it.

**Comment by DrudgeRajen** [comment]
@samundra Actually it was my confusion. If you use server and client in the same application then the client should have the flexibility of changing the ```$apipath```. Because you may have a collision of the same routes name if used default one. So, if the client is able to set the path then you can update the path of server manually and overcome the route name collision.
