### ISSUE TITLE
How to overide file checking

### ISSUE THREAD

**Issue by alexandrelgy** [ankitpokhrel/tus-php#99]
Hi,

I was wondering after reading the doc and implementing tus-php with your help, how would it be possible to upload the same file several times in dev environment.

I'm running your example file I adapted under laravel. 
Each time I try to upload a file that has already been sent, verify request is the only hit and returns Uploaded: 100.00% in js console and i would like it to be uploaded anyway. 

I implemented it using default cache config and not dis. 
Browser cache has been emptied, and tus:expired has already been run. 

Thanks in advance !

**Comment by samundra** [comment]
@alexandrelgy If you are trying to upload same file on the same upload directory then you have to clear the cache and also delete the file from the server upload directory everytime before upload from the client.

**Comment by alexandrelgy** [comment]
I've already cleared browser cache, run tus:expired and deleted files from directories(forgot to mention last one sorry).
Each time file has done uploading, it is moved to another custom directory with a custom mtdir function.

[controller.txt](https://github.com/ankitpokhrel/tus-php/files/2525577/controller.txt)
[js.txt](https://github.com/ankitpokhrel/tus-php/files/2525578/js.txt)

**Comment by samundra** [comment]
@alexandrelgy Can you please share the code on pastebin.com or somewhere in online and remove the attached link to downloadable files.

And after removing the browser cache also you were unable to upload files?

**Comment by alexandrelgy** [comment]
Thanks for sharing good practices. I've edited my post.

> And after removing the browser cache also you were unable to upload files?

No neither ! The TusFile sends a uploaded 100% message.

**Comment by ankitpokhrel** [comment]
> Browser cache has been emptied, and tus:expired has already been run.

@alexandrelgy There is no relation with browser cache and `tus:expired` will only delete expired uploads. Default TTL is 1 day.

You need to delete server cache to upload same file again. For `redis` you can connect to redis server and delete the entry. If you are using file cache then you can delete `.cache/tus_php.cache` file.
